// Stats page (regione -> provincia -> comune drill-down + comparison +
// per-comune priority-intervention street list), backed by three
// national rollup files generated by scripts/build_comuni_stats.py and
// scripts/build_regional_stats.py (web/data/italia_{regione,provincia,
// comuni}_stats.json) plus one small per-comune file generated by
// scripts/build_comuni_interventions.py (web/data/interventions/
// <istat_code>.json), fetched only when that comune's detail is opened.
//
// Fully localized via I18N (i18n.js) like the rest of the site - every
// user-facing string here goes through t()/tf(), including chart titles,
// table headers and the LTS/excluded-km/highway-type labels baked into
// chart data. render() is re-run in full on a language change (see the
// lang-select handler in init()) rather than trying to patch text nodes
// in place, since almost every DOM node on this page is templated string
// HTML rebuilt from state anyway.

// Italy-wide constants used only for the coverage note - these are
// stable geographic facts (comuni/province/regioni counts), not derived
// from the partial dataset, which currently only covers a handful of
// regioni.
const ITALY_TOTAL_COMUNI = 7896;
const ITALY_TOTAL_PROVINCE = 107;
const ITALY_TOTAL_REGIONI = 20;

const LTS_COLORS = { "1": "#146C36", "2": "#A6B32C", "3": "#CC7722", "4": "#B7231F", "0": "#6B6B6B" };

function ltsLabel(cls) {
  return t(`statsLts${cls}`);
}

// "Non-cyclable" deliberately merges two different pipeline concepts into
// one chart: the four excluded_* buckets (roads dropped before LTS
// classification even runs - motorroad, mountain trail, restricted
// access, service road) AND km_by_lts["0"] (roads that reached
// classification but came out "not allowed/not applicable"). Both are km
// nobody can actually cycle on right now, which is the question this
// chart answers - the pipeline's internal distinction between "excluded"
// and "classified as 0" isn't something a comune needs to care about.
function excludedFields() {
  return [
    { key: "excluded_mountain_trail_km", label: t("statsExclMountainTrail"), color: "#5C6BC0", value: (r) => r.excluded_mountain_trail_km || 0 },
    { key: "excluded_motorroad_km", label: t("statsExclMotorroad"), color: "#8D6E63", value: (r) => r.excluded_motorroad_km || 0 },
    { key: "excluded_restricted_access_km", label: t("statsExclRestrictedAccess"), color: "#78909C", value: (r) => r.excluded_restricted_access_km || 0 },
    { key: "excluded_service_road_km", label: t("statsExclServiceRoad"), color: "#26A69A", value: (r) => r.excluded_service_road_km || 0 },
    { key: "lts0", label: t("statsExclNotAllowed"), color: LTS_COLORS["0"], value: (r) => (r.km_by_lts && r.km_by_lts["0"]) || 0 },
  ];
}
function nonCyclableKm(row) {
  return excludedFields().reduce((sum, f) => sum + f.value(row), 0);
}

// scripts/build_comuni_interventions.py names web/data/interventions/
// files by istat_code, but the main map (web/index.html) is keyed by
// name-derived slug (?area=<slug>, matching <slug>_lts.pmtiles) - mirrors
// domain/area_spec.py::slugify exactly (NFKD-normalize, drop combining
// marks, spaces to underscores, strip anything else unsafe) so the link
// always resolves to a real tileset.
function areaSlug(name) {
  return name
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/ /g, "_")
    .replace(/[^A-Za-z0-9_.-]/g, "");
}

const HIGHWAY_KEY_MAP = {
  residential: "statsHwResidential",
  living_street: "statsHwLivingStreet",
  unclassified: "statsHwUnclassified",
  tertiary: "statsHwTertiary",
  tertiary_link: "statsHwTertiaryLink",
  secondary: "statsHwSecondary",
  secondary_link: "statsHwSecondaryLink",
  primary: "statsHwPrimary",
  primary_link: "statsHwPrimaryLink",
  trunk: "statsHwTrunk",
  trunk_link: "statsHwTrunkLink",
  motorway: "statsHwMotorway",
  motorway_link: "statsHwMotorwayLink",
  service: "statsHwService",
  track: "statsHwTrack",
  path: "statsHwPath",
  footway: "statsHwFootway",
  cycleway: "statsHwCycleway",
  pedestrian: "statsHwPedestrian",
  steps: "statsHwSteps",
  bridleway: "statsHwBridleway",
  sconosciuto: "statsHwUnknown",
};

function highwayLabel(tag) {
  const key = HIGHWAY_KEY_MAP[tag];
  return key ? t(key) : tag ? tag.charAt(0).toUpperCase() + tag.slice(1) : t("statsHwOther");
}

const CENTRALITY_KEY_MAP = {
  zero: "statsCentralityZero",
  low: "statsCentralityLow",
  medium: "statsCentralityMedium",
  high: "statsCentralityHigh",
  very_high: "statsCentralityVeryHigh",
};
function centralityLabel(cls) {
  const key = CENTRALITY_KEY_MAP[cls];
  return key ? t(key) : cls ?? "-";
}

function localeForLang(lang) {
  return { it: "it-IT", en: "en-GB", de: "de-DE", fr: "fr-FR" }[lang] || "it-IT";
}
function fmtKm(v) { return v == null ? "-" : `${v.toFixed(1)} km`; }
function fmtKm2(v) { return v == null ? "-" : `${v.toFixed(1)} km²`; }
function fmtPercent(v) { return v == null ? "-" : `${Math.round(v * 100)}%`; }
function fmtInt(v) { return v == null ? "-" : Math.round(v).toLocaleString(localeForLang(currentLang())); }

// LTS0 (red) -> LTS1 (green) linear interpolation, reused so every
// share-driven color (treemap, scatter) reads consistently with the
// on-map LTS palette (low share = same alarm-red as LTS4, high share =
// the same calm green as LTS1).
function shareToColor(share) {
  const bad = [0xb7, 0x23, 0x1f];
  const good = [0x14, 0x6c, 0x36];
  const frac = Math.max(0, Math.min(1, share ?? 0));
  const mix = bad.map((c, i) => Math.round(c + (good[i] - c) * frac));
  return `rgb(${mix.join(",")})`;
}

// --- i18n ---------------------------------------------------------------

function currentLang() {
  const params = new URLSearchParams(window.location.search);
  return params.get("lang") in I18N ? params.get("lang") : "it";
}
function t(key) {
  return I18N[currentLang()][key] ?? I18N.it[key];
}

// --- Data loading -----------------------------------------------------

const state = {
  regioni: [],
  province: [],
  comuni: [],
  clusters: [],
  currentRegione: null,
  currentProvincia: null,
  currentComuneIstat: null,
  compare: { level: null, items: new Map() }, // key -> {name, row}
};

function loadJson(path) {
  return fetch(path).then((r) => {
    if (!r.ok) throw new Error(`HTTP ${r.status} on ${path}`);
    return r.json();
  });
}

Promise.all([
  loadJson("../data/italia_regione_stats.json"),
  loadJson("../data/italia_provincia_stats.json"),
  loadJson("../data/italia_comuni_stats.json"),
  // Best-effort: the clusters section is a nice-to-have on the Italia
  // root view, not core navigation - if this file hasn't been generated
  // yet (scripts/build_comuni_clusters.py) the rest of the page should
  // still work, just without that one section.
  loadJson("../data/italia_comuni_clusters.json").catch(() => []),
])
  .then(([regioni, province, comuni, clusters]) => {
    state.regioni = regioni;
    state.province = province;
    state.comuni = comuni;
    state.clusters = clusters;
    init();
  })
  .catch((error) => {
    document.getElementById("view-root").innerHTML = `<p style="color:#b7231f">${t("statsLoadErrorTemplate")(error.message)}</p>`;
  });

function init() {
  applyStaticTranslations();
  document.getElementById("lang-select").addEventListener("change", (e) => {
    const url = new URL(window.location.href);
    url.searchParams.set("lang", e.target.value);
    window.history.replaceState({}, "", url);
    applyStaticTranslations();
    render();
    renderCompareTray();
  });
  setupSearch();
  setupCompareTray();
  setupShareBar();
  const setAboutOpen = setupInfoPanel("about-toggle", "about-panel", "about-close");
  const setFaqOpen = setupInfoPanel("faq-toggle", "faq-panel", "faq-close");
  setupInfoPanel("privacy-toggle", "privacy-panel", "privacy-close");
  setupInfoPanel("credits-toggle", "credits-panel", "credits-close");
  // "Dai un'occhiata alle FAQ" links inside aboutBody (i18n.js) - event
  // delegation since #about-body's innerHTML is replaced wholesale on
  // every applyStaticTranslations() call (language switch).
  document.getElementById("about-body").addEventListener("click", (e) => {
    if (!e.target.classList.contains("open-faq-link")) return;
    e.preventDefault();
    setAboutOpen(false);
    setFaqOpen(true);
  });
  restoreStateFromUrl();
  render();
}

// Same open/close wiring as the main site (web/app.js) - About, FAQ,
// Cookie/Privacy and Ringraziamenti/Credits all share the same centred
// .info-panel slot, so opening one closes whichever other one was open.
const infoPanelSetters = [];
function setupInfoPanel(toggleId, panelId, closeId) {
  const toggle = document.getElementById(toggleId);
  const panel = document.getElementById(panelId);
  function setOpen(open) {
    panel.classList.toggle("hidden", !open);
    toggle.classList.toggle("active", open);
    if (open) {
      for (const otherSetOpen of infoPanelSetters) {
        if (otherSetOpen !== setOpen) otherSetOpen(false);
      }
    }
  }
  infoPanelSetters.push(setOpen);
  toggle.addEventListener("click", () => setOpen(panel.classList.contains("hidden")));
  if (closeId) document.getElementById(closeId).addEventListener("click", () => setOpen(false));
  return setOpen;
}

// Own web/stats/faq.json, NOT the main site's web/faq.json - this page's
// FAQ goes deeper into stats-specific questions (cluster methodology,
// what "quota a basso stress" means, how priority streets are picked,
// data licensing) that don't belong on the main map's own FAQ. Same
// cache-once shape as web/app.js's ensureFaqLoaded otherwise. Italian
// only, same convention as the main site's faq.json (see that file's own
// "Italian only for now" comment in i18n.js) - not covered by
// aiTranslationNote, since it isn't translated at all yet.
let faqItems = null;
let faqItemsPromise = null;
function ensureFaqLoaded() {
  if (faqItems) return Promise.resolve(faqItems);
  if (!faqItemsPromise) {
    faqItemsPromise = fetch(new URL("faq.json", window.location.href))
      .then((response) => response.json())
      .then((data) => {
        faqItems = data;
        return data;
      })
      .catch(() => {
        faqItemsPromise = null;
        return [];
      });
  }
  return faqItemsPromise;
}
ensureFaqLoaded().then(renderFaq);

function renderFaq() {
  const list = document.getElementById("faq-list");
  if (!list) return;
  list.innerHTML = "";
  for (const item of faqItems || []) {
    const wrapper = document.createElement("div");
    wrapper.className = "faq-item";
    const question = document.createElement("button");
    question.type = "button";
    question.className = "faq-question";
    question.textContent = item.q;
    const answer = document.createElement("div");
    answer.className = "faq-answer hidden";
    answer.innerHTML = item.a;

    const closeLink = document.createElement("button");
    closeLink.type = "button";
    closeLink.className = "faq-close-answer";
    closeLink.textContent = t("faqCloseAndScrollUp");
    closeLink.addEventListener("click", () => {
      wrapper.classList.remove("open");
      answer.classList.add("hidden");
      document.getElementById("faq-panel").scrollTo({ top: 0, behavior: "smooth" });
    });
    answer.appendChild(closeLink);

    question.addEventListener("click", () => {
      const isOpen = wrapper.classList.toggle("open");
      answer.classList.toggle("hidden", !isOpen);
      if (isOpen) wrapper.scrollIntoView({ behavior: "smooth", block: "center" });
    });
    wrapper.append(question, answer);
    list.appendChild(wrapper);
  }
}

// Deep-linking: a shared stats.js URL carries regione/provincia/comune
// (istat_code) query params, read once here before the first render so
// the page opens straight into the shared view instead of always
// starting at the Italia root. render() itself keeps these params in
// sync on every navigation (see syncUrlState below), so the address bar
// - and therefore the share bar's links - always reflect what's on
// screen, no separate "share this view" state to maintain.
function restoreStateFromUrl() {
  const params = new URLSearchParams(window.location.search);
  const comuneIstat = params.get("comune");
  const provincia = params.get("provincia");
  const regione = params.get("regione");
  if (comuneIstat && state.comuni.some((c) => c.istat_code === comuneIstat)) {
    const comune = state.comuni.find((c) => c.istat_code === comuneIstat);
    state.currentRegione = comune.regione;
    state.currentProvincia = comune.provincia;
    state.currentComuneIstat = comuneIstat;
  } else if (provincia && state.province.some((p) => p.area === provincia)) {
    state.currentRegione = state.province.find((p) => p.area === provincia).regione;
    state.currentProvincia = provincia;
  } else if (regione && state.regioni.some((r) => r.area === regione)) {
    state.currentRegione = regione;
  }
}

function syncUrlState() {
  const url = new URL(window.location.href);
  const params = url.searchParams;
  ["regione", "provincia", "comune"].forEach((key) => params.delete(key));
  if (state.currentRegione) params.set("regione", state.currentRegione);
  if (state.currentProvincia) params.set("provincia", state.currentProvincia);
  if (state.currentComuneIstat) params.set("comune", state.currentComuneIstat);
  window.history.replaceState({}, "", url);
  renderShareBar();
}

// Text that doesn't depend on drill-down state - nav, page intro, search
// placeholder. Everything else is rebuilt by render() itself, since it's
// templated HTML generated from state rather than static markup.
function applyStaticTranslations() {
  const lang = currentLang();
  document.documentElement.lang = lang;
  document.getElementById("lang-select").value = lang;
  document.title = `Stress in bici - ${t("statsNavLink")}`;
  document.getElementById("stats-link").textContent = t("statsNavLink");
  document.getElementById("footer-credit").innerHTML = t("footerCredit");
  document.getElementById("footer-hosting-text").textContent = t("footerHosting");
  document.getElementById("page-title").textContent = t("statsPageTitle");
  document.getElementById("page-subtitle").textContent = t("statsPageSubtitle");
  document.getElementById("comune-search").placeholder = t("statsSearchPlaceholder");
  // Authored, static content from i18n.js (the OpenStreetMap link), not
  // user- or API-derived - same "nothing to sanitize" reasoning as
  // aboutBody/creditsBody's own innerHTML assignments below.
  document.getElementById("stats-data-note").innerHTML = t("statsDataNote");
  renderCoverageNote();
  document.getElementById("dataset-download-title").textContent = t("statsDatasetDownloadTitle");
  document.getElementById("dataset-download-note").innerHTML = t("statsDatasetDownloadNote");
  document.getElementById("dataset-download-label").textContent = t("statsDatasetDownloadButton");

  // Dedicated stats*-prefixed keys, NOT the main site's aboutToggle/
  // aboutHeading/aboutSubtitle/aboutBody - this page's About references
  // the main project (link back) and explains what statistics are
  // computed here; it deliberately doesn't retell the project's own
  // history, already told on the main site's About.
  document.getElementById("about-toggle").textContent = t("aboutToggle");
  document.getElementById("about-heading").textContent = t("statsAboutHeading");
  document.getElementById("about-subtitle").textContent = t("statsAboutSubtitle");
  // aboutBody/faqItems[].a/creditsBody/footerCredit are the only innerHTML
  // assignments here - authored, static content from i18n.js, not user-
  // or API-derived, so there's nothing to sanitize against.
  document.getElementById("about-body").innerHTML = t("statsAboutBody");
  document.getElementById("faq-toggle").textContent = t("faqToggle");
  document.getElementById("faq-heading").textContent = t("faqHeading");
  renderFaq();
  // Italian is the original text; every other language is an AI
  // translation of it - disclosed here rather than left implicit (see
  // web/app.js's applyUiTranslations for the same note on the main site).
  const aiNote = lang === "it" ? "" : t("aiTranslationNote") || "";
  document.getElementById("about-ai-note").textContent = aiNote;
  document.getElementById("about-ai-note").classList.toggle("hidden", !aiNote);
  document.getElementById("faq-ai-note").textContent = aiNote;
  document.getElementById("faq-ai-note").classList.toggle("hidden", !aiNote);
  document.getElementById("privacy-toggle").textContent = t("privacyToggle");
  document.getElementById("privacy-heading").textContent = t("privacyHeading");
  document.getElementById("privacy-intro").textContent = t("privacyIntro");
  document.getElementById("credits-toggle").textContent = t("creditsToggle");
  document.getElementById("credits-heading").textContent = t("creditsHeading");
  document.getElementById("credits-body").innerHTML = t("creditsBody");
  document.getElementById("credits-ai-note").textContent = aiNote;
  document.getElementById("credits-ai-note").classList.toggle("hidden", !aiNote);
}

function renderCoverageNote() {
  const processed = state.regioni.reduce((s, r) => s + r.comuni_processed, 0);
  const regioniCount = state.regioni.length;
  const provinceCount = state.province.length;
  document.getElementById("coverage-note").textContent = t("statsCoverageNoteTemplate")(
    fmtInt(processed),
    ITALY_TOTAL_COMUNI,
    provinceCount,
    ITALY_TOTAL_PROVINCE,
    regioniCount,
    ITALY_TOTAL_REGIONI
  );
}

// --- Chart instance cache ----------------------------------------------

const chartInstances = new Map();
function getChart(containerId) {
  let inst = chartInstances.get(containerId);
  const el = document.getElementById(containerId);
  if (!el) return null;
  if (!inst || inst.getDom() !== el) {
    inst = echarts.init(el);
    chartInstances.set(containerId, inst);
  }
  return inst;
}
window.addEventListener("resize", () => {
  for (const inst of chartInstances.values()) inst.resize();
});

// --- Shared chart extras: fullscreen, download, optional dataZoom --------
//
// Every chart on this page goes through applyChartOption() instead of
// calling chart.setOption() directly, so the toolbox (fullscreen +
// "download as image", the latter a built-in echarts feature) is
// available everywhere without repeating this block at each of the
// dozen-plus call sites. dataZoom (a vertical slider on the category
// axis) is opt-in per call - only the ranked-bar-style charts whose
// item count scales with the drill-down level (a comune-level view can
// have hundreds of rows) need it; a handful of comparison bars or a
// single-category stacked bar don't.
//
// Straight-line-only SVG path (M/L commands, no arcs) for the fullscreen
// icon - four corner brackets - since zrender's path parser is pickier
// about arc syntax than a browser's own SVG renderer.
const CHART_FULLSCREEN_ICON =
  "path://M4,4 L4,10 M4,4 L10,4 M20,4 L20,10 M20,4 L14,4 M4,20 L4,14 M4,20 L10,20 M20,20 L20,14 M20,20 L14,20";

function chartToolboxOption() {
  return {
    right: 8,
    top: 4,
    itemSize: 14,
    feature: {
      saveAsImage: { title: t("statsChartDownload") },
      myFullscreen: {
        show: true,
        title: t("statsChartFullscreen"),
        icon: CHART_FULLSCREEN_ICON,
        onclick(ecModel, api) {
          toggleChartFullscreen(api.getDom().id);
        },
      },
    },
  };
}

// Sets the CSS custom properties the .chart-fullscreen rule reads for
// its (!important) top/left/right/bottom, leaving room for the sticky
// header and the floating share-bar rather than covering them. Custom
// properties, not plain inline style properties, because echarts
// reasserts an inline `position: relative` on this same element on
// every chart.resize() call (not just at init) - a plain inline
// position/top/etc would get silently stomped moments after we set it.
function positionFullscreenChart(el) {
  const gap = 16;
  const header = document.getElementById("site-header");
  const shareBar = document.getElementById("share-bar");
  const headerRect = header.getBoundingClientRect();
  const narrow = window.matchMedia("(max-width: 700px)").matches;
  const shareBarRect = shareBar.getBoundingClientRect();
  el.style.setProperty("--fs-top", `${headerRect.bottom + gap}px`);
  el.style.setProperty("--fs-left", `${gap}px`);
  if (narrow) {
    // Share-bar drops to a bottom row on narrow screens (see the
    // @media rule above) - reserve space below instead of on the right.
    el.style.setProperty("--fs-right", `${gap}px`);
    el.style.setProperty("--fs-bottom", `${window.innerHeight - shareBarRect.top + gap}px`);
  } else {
    el.style.setProperty("--fs-right", `${window.innerWidth - shareBarRect.left + gap}px`);
    el.style.setProperty("--fs-bottom", `${gap}px`);
  }
}

function fullscreenResizeHandler() {
  const el = document.querySelector(".chart-fullscreen");
  if (!el) return;
  positionFullscreenChart(el);
  const chart = chartInstances.get(el.id);
  if (chart) chart.resize();
}

function toggleChartFullscreen(containerId) {
  const el = document.getElementById(containerId);
  if (!el) return;
  const entering = !el.classList.contains("chart-fullscreen");
  el.classList.toggle("chart-fullscreen", entering);
  document.body.classList.toggle("has-fullscreen-chart", entering);
  document.documentElement.classList.toggle("has-fullscreen-chart", entering);
  if (entering) {
    positionFullscreenChart(el);
    window.addEventListener("resize", fullscreenResizeHandler);
  } else {
    window.removeEventListener("resize", fullscreenResizeHandler);
  }
  const chart = chartInstances.get(containerId);
  // Container size changes with the class toggle - echarts needs an
  // explicit resize() once that's actually taken effect, not before.
  // (chart.resize() also re-asserts inline position:relative on `el` -
  // harmless now, since the fullscreen rule's position:fixed is
  // !important and always wins regardless of what echarts sets inline.)
  setTimeout(() => chart && chart.resize(), 60);
}
document.addEventListener("keydown", (e) => {
  if (e.key !== "Escape") return;
  const el = document.querySelector(".chart-fullscreen");
  if (el) toggleChartFullscreen(el.id);
});

// dataZoom's default `end` shows every item at once, which is exactly
// the "molto pieni" (too full) problem for a comune-level view with
// hundreds of rows - defaults instead to whatever fraction shows about
// VISIBLE_BY_DEFAULT items, so a long list opens already scrollable/
// zoomable instead of squished.
const DATAZOOM_VISIBLE_BY_DEFAULT = 18;

function applyChartOption(chart, option, { dataZoom = false } = {}) {
  const merged = { ...option, toolbox: chartToolboxOption() };
  if (dataZoom) {
    const categoryCount = (option.yAxis && option.yAxis.data && option.yAxis.data.length) || 0;
    const end = categoryCount > DATAZOOM_VISIBLE_BY_DEFAULT ? (DATAZOOM_VISIBLE_BY_DEFAULT / categoryCount) * 100 : 100;
    merged.dataZoom = [
      { type: "slider", yAxisIndex: 0, width: 10, right: 8, top: 28, bottom: 8, start: 0, end, showDetail: false },
      { type: "inside", yAxisIndex: 0, start: 0, end },
    ];
  }
  chart.setOption(merged, true);
}

// --- Navigation / breadcrumb --------------------------------------------

function goRegione(regione) {
  state.currentRegione = regione;
  state.currentProvincia = null;
  state.currentComuneIstat = null;
  render();
}
function goProvincia(regione, provincia) {
  state.currentRegione = regione;
  state.currentProvincia = provincia;
  state.currentComuneIstat = null;
  render();
}
function goComune(istatCode) {
  const comune = state.comuni.find((c) => c.istat_code === istatCode);
  if (!comune) return;
  state.currentRegione = comune.regione;
  state.currentProvincia = comune.provincia;
  state.currentComuneIstat = istatCode;
  render();
}
function goRoot() {
  state.currentRegione = null;
  state.currentProvincia = null;
  state.currentComuneIstat = null;
  render();
}

function renderBreadcrumb() {
  const el = document.getElementById("breadcrumb");
  el.innerHTML = "";
  const crumbs = [{ label: t("statsBreadcrumbItalia"), onClick: goRoot }];
  if (state.currentRegione) crumbs.push({ label: state.currentRegione, onClick: () => goRegione(state.currentRegione) });
  if (state.currentProvincia) crumbs.push({ label: state.currentProvincia, onClick: () => goProvincia(state.currentRegione, state.currentProvincia) });
  if (state.currentComuneIstat) {
    const comune = state.comuni.find((c) => c.istat_code === state.currentComuneIstat);
    if (comune) crumbs.push({ label: comune.comune, onClick: null });
  }
  crumbs.forEach((c, i) => {
    if (i > 0) el.appendChild(document.createTextNode(" "));
    const btn = document.createElement("button");
    btn.textContent = c.label;
    const isLast = i === crumbs.length - 1;
    btn.disabled = isLast;
    if (!isLast) btn.addEventListener("click", c.onClick);
    el.appendChild(btn);
    if (!isLast) {
      const sep = document.createElement("span");
      sep.className = "crumb-sep";
      sep.textContent = "›";
      el.appendChild(sep);
    }
  });
}

function render() {
  syncUrlState();
  renderBreadcrumb();
  const root = document.getElementById("view-root");
  root.innerHTML = "";

  if (state.currentComuneIstat) {
    renderComuneDetail(root, state.currentComuneIstat);
    return;
  }
  if (state.currentProvincia) {
    const items = state.comuni.filter((c) => c.provincia === state.currentProvincia);
    renderLevelView(root, items, "comune", t("statsComuniOfTemplate")(state.currentProvincia));
    return;
  }
  if (state.currentRegione) {
    const items = state.province.filter((p) => p.regione === state.currentRegione);
    renderLevelView(root, items, "provincia", t("statsProvinceOfTemplate")(state.currentRegione));
    return;
  }
  renderClustersSection(root);
  renderLevelView(root, state.regioni, "regione", t("statsRootTitle"));
}

// --- Peer-comuni clusters (Italia root view only) --------------------
//
// scripts/build_comuni_clusters.py groups comuni into size-based peer
// groups - two fixed population tiers ("Grandi città", "Città grandi")
// plus 5 k-means tiers (on log-population/log-superficie) for everyone
// smaller - so "best/worst by low_stress_share" is a comparison between
// genuinely similar comuni instead of a single national ranking Roma
// would trivially dominate or vanish into. Purely presentational here -
// all the grouping/ranking already happened in Python; this just renders
// whatever tiers are in the file (state.clusters.length, not a fixed 5).
function renderClustersSection(root) {
  if (!state.clusters.length) return;

  const section = document.createElement("div");
  section.className = "card-panel";
  section.innerHTML = `
    <h2>${t("statsClustersTitle")}</h2>
    <p class="chart-note">${t("statsClustersNoteTemplate")(state.clusters.length)}</p>
    <div id="clusters-grid" class="charts-grid"></div>
  `;
  root.appendChild(section);

  const grid = section.querySelector("#clusters-grid");
  const CLUSTER_PAGE_SIZE = 3;
  state.clusters.forEach((cluster) => {
    const card = document.createElement("div");
    card.className = "card-panel";
    // Metropoli/Grandi città/Città grandi are defined by a REAL fixed
    // population threshold (build_comuni_clusters.py's own
    // popolazione_soglia_min/max) - state that exact rule rather than
    // the interquartile range, which for these 3 reads like an
    // approximation of something that's actually an exact cutoff. The
    // 6 k-means tiers have no such rule (see that script's own
    // docstring), so they keep the percentile-based "circa" phrasing -
    // the only honest description available for a cluster shaped by the
    // current comuni set rather than a fixed definition.
    const rangeText = cluster.popolazione_soglia_min != null
      ? cluster.popolazione_soglia_max != null
        ? t("statsClusterThresholdRangeTemplate")(fmtInt(cluster.popolazione_soglia_min), fmtInt(cluster.popolazione_soglia_max), cluster.superficie_p25, cluster.superficie_p75)
        : t("statsClusterThresholdMinTemplate")(fmtInt(cluster.popolazione_soglia_min), cluster.superficie_p25, cluster.superficie_p75)
      : t("statsClusterRangeTemplate")(fmtInt(cluster.popolazione_p25), fmtInt(cluster.popolazione_p75), cluster.superficie_p25, cluster.superficie_p75);
    card.innerHTML = `
      <h2>${cluster.label}</h2>
      <p class="chart-note">
        ${rangeText}
        · ${t("statsClusterCountTemplate")(fmtInt(cluster.comuni_count))}
      </p>
      <div class="cluster-lists">
        <div>
          <h3>${t("statsClusterBestLabel")}</h3>
          <ol class="cluster-list" data-kind="top"></ol>
        </div>
        <div>
          <h3>${t("statsClusterWorstLabel")}</h3>
          <ol class="cluster-list" data-kind="bottom"></ol>
        </div>
      </div>
      <div class="cluster-pager">
        <button type="button" data-dir="-1" title="${t("statsClusterPagerPrev")}">${SORT_ARROW_UP}</button>
        <button type="button" data-dir="1" title="${t("statsClusterPagerNext")}">${SORT_ARROW_DOWN}</button>
      </div>
    `;
    grid.appendChild(card);

    // Both columns page together (one shared offset), in blocks of
    // CLUSTER_PAGE_SIZE, further into the same top/bottom-sorted lists
    // build_comuni_clusters.py already exports (up to TOP_N members deep
    // on each side) - not just the fixed top-3/bottom-3 shown before.
    const topList = card.querySelector('[data-kind="top"]');
    const bottomList = card.querySelector('[data-kind="bottom"]');
    const upBtn = card.querySelector('.cluster-pager button[data-dir="-1"]');
    const downBtn = card.querySelector('.cluster-pager button[data-dir="1"]');
    const maxOffset = Math.max(0, cluster.top.length - CLUSTER_PAGE_SIZE);
    let offset = 0;
    // The rank/name/% swap instantly on click - correct, but with no
    // motion or highlight at all it read as "nothing happened" (reported
    // live: pressing the pager didn't look like it did anything, even
    // though the list content was in fact updating). A brief fade
    // (CSS transition on .cluster-list's opacity, see index.html) makes
    // the update visible without a real scroll animation, which wouldn't
    // fit "jump to the next block of 3" anyway.
    function renderPage() {
      [topList, bottomList].forEach((el) => el.classList.add("cluster-list-updating"));
      renderClusterList(topList, cluster.top.slice(offset, offset + CLUSTER_PAGE_SIZE), true, offset, cluster.comuni_count);
      renderClusterList(bottomList, cluster.bottom.slice(offset, offset + CLUSTER_PAGE_SIZE), false, offset, cluster.comuni_count);
      upBtn.disabled = offset <= 0;
      downBtn.disabled = offset >= maxOffset;
      requestAnimationFrame(() => {
        [topList, bottomList].forEach((el) => el.classList.remove("cluster-list-updating"));
      });
    }
    upBtn.addEventListener("click", () => {
      offset = Math.max(0, offset - CLUSTER_PAGE_SIZE);
      renderPage();
    });
    downBtn.addEventListener("click", () => {
      offset = Math.min(maxOffset, offset + CLUSTER_PAGE_SIZE);
      renderPage();
    });
    renderPage();
  });
}

function renderClusterList(listEl, items, isBest, offset, comuniCount) {
  listEl.innerHTML = items
    .map((item, i) => {
      // The "top" list is already sorted best-first, so its position in
      // the array IS its classification rank (1st, 2nd, ...). "bottom" is
      // the tail of that same ranking reversed (worst-first for display),
      // so its true rank counts down from comuni_count instead - showing
      // "1, 2, 3..." there would read as if the worst comune were #1
      // (best), when it's actually dead last.
      const rank = isBest ? offset + i + 1 : comuniCount - offset - i;
      const trophy = isBest && rank === 1 ? `<span title="${t("statsClusterTrophyTitle")}">🏆</span> ` : "";
      // Two comuni can both round to "92%" (fmtPercent has no decimals) -
      // the precise value, PLUS the actual km it represents (not exported
      // per-cluster-member, so derived from the two fields that are:
      // total_km * low_stress_share), only shows on hover (native title
      // tooltip, no extra UI needed) so it's there when someone wonders
      // why a tied-looking #1 and #2 aren't in the order they expected,
      // or just wants the absolute km behind the percentage.
      const preciseShare = item.low_stress_share != null ? `${(item.low_stress_share * 100).toFixed(3)}%` : "-";
      const shareTitle =
        item.low_stress_share != null && item.total_km != null
          ? t("statsClusterShareTooltipTemplate")(preciseShare, fmtKm(item.total_km * item.low_stress_share), fmtKm(item.total_km))
          : preciseShare;
      // Same idea for the comune name - population/superficie aren't
      // shown anywhere in this compact row (that's what makes the
      // cluster comparable at all, see the card's own range note above),
      // but are one hover away for whoever wants the absolute numbers
      // behind "this comune, this cluster".
      const nameTitle = t("statsClusterNameTooltipTemplate")(fmtInt(item.popolazione), fmtKm2(item.superficie_km2));
      return `<li>
        <span class="cluster-item-rank">${rank}</span>
        <span class="cluster-item-name" title="${nameTitle}">${trophy}${item.comune}</span>
        <span class="cluster-item-meta">
          <span class="cluster-item-provincia" data-idx="${i}">${item.provincia}</span> · <span title="${shareTitle}">${fmtPercent(item.low_stress_share)}</span>
        </span>
      </li>`;
    })
    .join("");
  listEl.querySelectorAll("li").forEach((li, i) => {
    li.addEventListener("click", () => goComune(items[i].istat_code));
  });
  // Own click handler + stopPropagation so clicking the provincia name
  // opens that provincia's view instead of (or as well as) the comune's -
  // the two need to lead somewhere different, not just the same comune
  // detail the rest of the row already opens.
  listEl.querySelectorAll(".cluster-item-provincia").forEach((el) => {
    el.addEventListener("click", (e) => {
      e.stopPropagation();
      const item = items[Number(el.dataset.idx)];
      goProvincia(item.regione, item.provincia);
    });
  });
}

function itemName(row, level) {
  return level === "comune" ? row.comune : row.area;
}
function itemKey(row, level) {
  return level === "comune" ? row.istat_code : row.area;
}

// --- Level view: charts + table ------------------------------------------

// Each of the 5 ranked-bar-style charts sorts independently now (the
// user didn't want one control driving all of them in lockstep) by
// either its own value metric or alphabetically, each with its own
// ascending/descending flip-flop rather than a separate button per
// direction. valueOf is the metric that chart's bars actually encode;
// defaultDir is whichever direction that chart originally always used
// (kept as the starting point so nothing visually changes until the
// user actually touches a toggle) - e.g. the LTS-stack and excluded-km
// charts default to descending (biggest network first) while share/
// density/per-capita default to ascending (echarts renders yAxis
// category index 0 at the bottom, so ascending puts the "best" value
// at the top of the bar list).
const RANKED_CHART_CONFIGS = {
  "chart-ranked": { valueOf: (r) => r.low_stress_share ?? 0, defaultDir: 1, draw: () => drawRankedBar(sortItems, sortLevel) },
  "chart-lts-stack": { valueOf: (r) => r.total_km ?? 0, defaultDir: -1, draw: () => drawLtsStack(sortItems, sortLevel) },
  "chart-excluded": { valueOf: (r) => nonCyclableKm(r), defaultDir: -1, draw: () => drawExcludedStack(sortItems, sortLevel) },
  "chart-density": { valueOf: (r) => density(r), defaultDir: 1, draw: () => drawDensity(sortItems, sortLevel) },
  "chart-per-capita": { valueOf: (r) => perCapita(r), defaultDir: 1, draw: () => drawPerCapita(sortItems, sortLevel) },
};
let chartSortState = {};
// The items/level the toggles above close over - set once per
// renderLevelView call, read by RANKED_CHART_CONFIGS' draw() thunks so
// a single chart's toggle can redraw just that chart without needing
// its own copy of the current items/level.
let sortItems = [];
let sortLevel = null;

// Chart height used to grow unbounded with item count
// (Math.max(220, items.length*22)) - fine for ~20 regioni, unusable for
// a large provincia's ~150+ comuni (the "molto pieni" the user flagged).
// Capped now that the ranked charts carry their own dataZoom slider
// (applyChartOption's `dataZoom: true`) to scroll/zoom within a fixed
// height instead of the page just growing forever.
function rankedChartHeight(itemCount) {
  return Math.min(Math.max(220, itemCount * 22), 480);
}

function renderLevelView(root, items, level, title) {
  if (!items.length) {
    root.innerHTML += `<p>${t("statsNoDataForSelection")}</p>`;
    return;
  }
  // Fresh defaults on every new drill-down level, not carried over from
  // whatever the user last set on a different regione/provincia/comune.
  sortItems = items;
  sortLevel = level;
  chartSortState = Object.fromEntries(
    Object.entries(RANKED_CHART_CONFIGS).map(([id, cfg]) => [id, { field: "value", dir: cfg.defaultDir }])
  );

  const section = document.createElement("div");
  section.innerHTML = `<h2 style="margin:0 0 10px">${title}</h2>`;
  root.appendChild(section);

  const chartHeight = rankedChartHeight(items.length);
  const grid = document.createElement("div");
  grid.className = "charts-grid";
  grid.innerHTML = `
    <div class="card-panel">
      <h2>${t("statsChartRankedTitle")}</h2>
      <p class="chart-note">${t("statsChartRankedNote")}</p>
      <div class="chart-sort-toggle" data-chart="chart-ranked"></div>
      <div id="chart-ranked" class="chart-box" style="height:${chartHeight}px"></div>
    </div>
    <div class="card-panel">
      <h2>${t("statsChartLtsStackTitle")}</h2>
      <p class="chart-note">${t("statsChartLtsStackNote")}</p>
      <div class="chart-sort-toggle" data-chart="chart-lts-stack"></div>
      <div id="chart-lts-stack" class="chart-box" style="height:${chartHeight}px"></div>
    </div>
    <div class="card-panel">
      <h2>${t("statsChartExcludedTitle")}</h2>
      <p class="chart-note">${t("statsChartExcludedNote")}</p>
      <div class="chart-sort-toggle" data-chart="chart-excluded"></div>
      <div id="chart-excluded" class="chart-box" style="height:${chartHeight}px"></div>
    </div>
    <div class="card-panel">
      <h2>${t("statsChartDensityTitle")}</h2>
      <p class="chart-note">${t("statsChartDensityNote")}</p>
      <div class="chart-sort-toggle" data-chart="chart-density"></div>
      <div id="chart-density" class="chart-box" style="height:${chartHeight}px"></div>
    </div>
    ${items.some((r) => r.popolazione) ? `
    <div class="card-panel">
      <h2>${t("statsChartPerCapitaTitle")}</h2>
      <p class="chart-note">${t("statsChartPerCapitaNote")}</p>
      <div class="chart-sort-toggle" data-chart="chart-per-capita"></div>
      <div id="chart-per-capita" class="chart-box" style="height:${chartHeight}px"></div>
    </div>` : ""}
    <div class="card-panel">
      <h2>${t("statsChartScatterTitle")}</h2>
      <p class="chart-note">${t("statsChartScatterNote")}</p>
      <div id="chart-scatter" class="chart-box" style="height:320px"></div>
    </div>
  `;
  root.appendChild(grid);
  grid.querySelectorAll(".chart-sort-toggle").forEach((toggle) => renderSortToggle(toggle, toggle.dataset.chart));

  const treemapPanel = document.createElement("div");
  treemapPanel.className = "card-panel";
  treemapPanel.innerHTML = `
    <h2>${t("statsChartTreemapTitle")}</h2>
    <p class="chart-note">${t("statsChartTreemapNote")}</p>
    <div id="chart-treemap" class="chart-box" style="height:420px"></div>
  `;
  root.appendChild(treemapPanel);

  redrawRankedCharts(items, level);
  drawScatter(items, level);
  drawTreemap(items, level);

  renderTable(root, items, level);
}

function redrawRankedCharts(items, level) {
  drawRankedBar(items, level);
  drawLtsStack(items, level);
  drawExcludedStack(items, level);
  drawDensity(items, level);
  if (items.some((r) => r.popolazione)) drawPerCapita(items, level);
}

const SORT_ARROW_UP = "▲";
const SORT_ARROW_DOWN = "▼";

// Renders (or re-renders after a click) one chart's own Nome/Valore
// toggle. Each button doubles as the direction flip - clicking the
// already-active one flips its arrow/order, clicking the other one
// switches field instead (starting from that chart's own default
// direction for "Valore", or A->Z for "Nome").
function renderSortToggle(toggle, chartId) {
  const state = chartSortState[chartId];
  const arrow = state.dir === 1 ? SORT_ARROW_UP : SORT_ARROW_DOWN;
  const label = (field) => `${field === "value" ? t("statsSortByValue") : t("statsSortByName")}${state.field === field ? ` <span class="sort-arrow">${arrow}</span>` : ""}`;
  toggle.innerHTML = `
    <button type="button" data-field="value" class="${state.field === "value" ? "active" : ""}">${label("value")}</button>
    <button type="button" data-field="name" class="${state.field === "name" ? "active" : ""}">${label("name")}</button>
  `;
  toggle.querySelectorAll("button").forEach((btn) => {
    btn.addEventListener("click", () => {
      const field = btn.dataset.field;
      if (state.field === field) {
        state.dir *= -1;
      } else {
        state.field = field;
        state.dir = field === "name" ? 1 : RANKED_CHART_CONFIGS[chartId].defaultDir;
      }
      renderSortToggle(toggle, chartId);
      RANKED_CHART_CONFIGS[chartId].draw();
    });
  });
}

function sortForChart(items, level, chartId) {
  const state = chartSortState[chartId];
  if (state.field === "name") {
    return [...items].sort((a, b) => state.dir * itemName(a, level).localeCompare(itemName(b, level), "it"));
  }
  const valueOf = RANKED_CHART_CONFIGS[chartId].valueOf;
  return [...items].sort((a, b) => state.dir * (valueOf(a) - valueOf(b)));
}

// Horizontal-bar charts reserve a fixed left margin for the category
// (name) axis labels - fine on desktop, but on a narrow phone screen a
// 160px label column leaves almost nothing for the bars themselves.
// hideOverlap on the value axis additionally lets echarts drop whichever
// tick labels would collide instead of letting them smash together.
function hbarLayout() {
  const narrow = window.innerWidth < 600;
  return { left: narrow ? 90 : 160, labelWidth: narrow ? 80 : 150 };
}

function drawRankedBar(items, level) {
  const chart = getChart("chart-ranked");
  const sorted = sortForChart(items, level, "chart-ranked");
  const layout1 = hbarLayout();
  applyChartOption(
    chart,
    {
      grid: { left: layout1.left, right: 50, top: 10, bottom: 20 },
      xAxis: { type: "value", max: 1, axisLabel: { formatter: (v) => `${Math.round(v * 100)}%`, hideOverlap: true } },
      yAxis: { type: "category", data: sorted.map((r) => itemName(r, level)), axisLabel: { width: layout1.labelWidth, overflow: "truncate" } },
      tooltip: {
        trigger: "item",
        formatter: (p) => {
          const row = sorted[p.dataIndex];
          return t("statsRankedTooltipTemplate")(p.name, fmtPercent(p.value), fmtKm(row.low_stress_km), fmtKm(row.total_km));
        },
      },
      series: [
        {
          type: "bar",
          data: sorted.map((r) => ({ value: r.low_stress_share ?? 0, itemStyle: { color: shareToColor(r.low_stress_share) } })),
          barMaxWidth: 18,
        },
      ],
    },
    { dataZoom: true }
  );
  chart.off("click");
  chart.on("click", (p) => onItemActivate(sorted[p.dataIndex], level));
}

function drawLtsStack(items, level) {
  const chart = getChart("chart-lts-stack");
  const sorted = sortForChart(items, level, "chart-lts-stack");
  const series = ["0", "1", "2", "3", "4"].map((cls) => ({
    name: ltsLabel(cls),
    type: "bar",
    stack: "lts",
    itemStyle: { color: LTS_COLORS[cls] },
    data: sorted.map((r) => (r.km_by_lts && r.km_by_lts[cls]) || 0),
  }));
  const layout2 = hbarLayout();
  applyChartOption(
    chart,
    {
      grid: { left: layout2.left, right: 50, top: 10, bottom: 20 },
      xAxis: { type: "value", axisLabel: { formatter: (v) => `${v} km`, hideOverlap: true } },
      yAxis: { type: "category", data: sorted.map((r) => itemName(r, level)), axisLabel: { width: layout2.labelWidth, overflow: "truncate" } },
      tooltip: { trigger: "axis", axisPointer: { type: "shadow" } },
      series,
    },
    { dataZoom: true }
  );
  chart.off("click");
  chart.on("click", (p) => onItemActivate(sorted[p.dataIndex], level));
}

function drawExcludedStack(items, level) {
  const chart = getChart("chart-excluded");
  const fields = excludedFields();
  const sorted = sortForChart(items, level, "chart-excluded");
  const series = fields.map((f) => ({
    name: f.label,
    type: "bar",
    stack: "excl",
    itemStyle: { color: f.color },
    data: sorted.map((r) => f.value(r)),
  }));
  const layout2 = hbarLayout();
  applyChartOption(
    chart,
    {
      grid: { left: layout2.left, right: 50, top: 10, bottom: 20 },
      xAxis: { type: "value", axisLabel: { formatter: (v) => `${v} km`, hideOverlap: true } },
      yAxis: { type: "category", data: sorted.map((r) => itemName(r, level)), axisLabel: { width: layout2.labelWidth, overflow: "truncate" } },
      tooltip: { trigger: "axis", axisPointer: { type: "shadow" } },
      series,
    },
    { dataZoom: true }
  );
  chart.off("click");
  chart.on("click", (p) => onItemActivate(sorted[p.dataIndex], level));
}

// Absolute km always favors whichever comune/provincia/regione is
// physically largest - not a useful ranking on its own. Two fair
// normalizations, shown as their own ranked charts rather than folded
// into the absolute-km one: density (km per km² of area) needs no data
// beyond what's already here, while the per-capita chart below (km per
// 1,000 residents) is the more direct answer to "which comune is
// actually well served", now that population_service.py sources ISTAT's
// POSAS bulk file.
function density(row) {
  return row.superficie_km2 ? row.total_km / row.superficie_km2 : 0;
}
function perCapita(row) {
  return row.popolazione ? (row.total_km / row.popolazione) * 1000 : 0;
}

function drawDensity(items, level) {
  const chart = getChart("chart-density");
  const sorted = sortForChart(items, level, "chart-density");
  const layoutD = hbarLayout();
  applyChartOption(
    chart,
    {
      grid: { left: layoutD.left, right: 50, top: 10, bottom: 20 },
      xAxis: { type: "value", axisLabel: { formatter: (v) => `${v}`, hideOverlap: true } },
      yAxis: { type: "category", data: sorted.map((r) => itemName(r, level)), axisLabel: { width: layoutD.labelWidth, overflow: "truncate" } },
      tooltip: { formatter: (p) => t("statsDensityTooltipTemplate")(p.name, density(sorted[p.dataIndex]).toFixed(2)) },
      series: [{ type: "bar", data: sorted.map((r) => Number(density(r).toFixed(2))), itemStyle: { color: "#3B4A7A" }, barMaxWidth: 18 }],
    },
    { dataZoom: true }
  );
  chart.off("click");
  chart.on("click", (p) => onItemActivate(sorted[p.dataIndex], level));
}

function drawPerCapita(items, level) {
  const chart = getChart("chart-per-capita");
  const withPop = items.filter((r) => r.popolazione);
  const sorted = sortForChart(withPop, level, "chart-per-capita");
  const layoutP = hbarLayout();
  applyChartOption(
    chart,
    {
      grid: { left: layoutP.left, right: 50, top: 10, bottom: 20 },
      xAxis: { type: "value", axisLabel: { formatter: (v) => `${v}`, hideOverlap: true } },
      yAxis: { type: "category", data: sorted.map((r) => itemName(r, level)), axisLabel: { width: layoutP.labelWidth, overflow: "truncate" } },
      tooltip: { formatter: (p) => t("statsPerCapitaTooltipTemplate")(p.name, perCapita(sorted[p.dataIndex]).toFixed(2)) },
      series: [{ type: "bar", data: sorted.map((r) => Number(perCapita(r).toFixed(2))), itemStyle: { color: "#26A69A" }, barMaxWidth: 18 }],
    },
    { dataZoom: true }
  );
  chart.off("click");
  chart.on("click", (p) => onItemActivate(sorted[p.dataIndex], level));
}

// Single-level treemap (whatever `items` is showing at the current drill
// depth) rather than one giant regione->provincia->comune tree - lets the
// user zoom in one level at a time via goRegione/goProvincia/goComune,
// same as every other chart on this page, instead of a separate
// always-3-deep visualization that only ever made sense at the Italia
// root.
function drawTreemap(items, level) {
  const chart = getChart("chart-treemap");
  const data = items.map((r) => ({
    name: itemName(r, level),
    value: r.total_km,
    itemStyle: { color: shareToColor(r.low_stress_share) },
  }));
  applyChartOption(chart, {
    tooltip: { formatter: (p) => t("statsTreemapTooltipTemplate")(p.name, fmtKm(p.value)) },
    series: [
      {
        type: "treemap",
        roam: false,
        nodeClick: false,
        breadcrumb: { show: false },
        data,
      },
    ],
  });
  chart.off("click");
  chart.on("click", (p) => {
    const row = items.find((r) => itemName(r, level) === p.name);
    onItemActivate(row, level);
  });
}

function drawScatter(items, level) {
  const chart = getChart("chart-scatter");
  const maxKm = Math.max(1, ...items.map((r) => r.total_km || 0));
  applyChartOption(chart, {
    grid: { left: 55, right: 20, top: 20, bottom: 45 },
    xAxis: { type: "value", name: t("statsScatterXAxis"), min: 0, max: 1, axisLabel: { formatter: (v) => `${Math.round(v * 100)}%` } },
    yAxis: { type: "value", name: t("statsScatterYAxis") },
    tooltip: {
      formatter: (p) => t("statsScatterTooltipTemplate")(p.data.name, fmtPercent(p.data.value[0]), fmtKm(p.data.value[1]), fmtKm(p.data.value[2])),
    },
    series: [
      {
        type: "scatter",
        symbolSize: (val) => 8 + 32 * Math.sqrt((val[2] || 0) / maxKm),
        data: items.map((r) => ({
          name: itemName(r, level),
          value: [r.low_stress_share ?? 0, r.priority_intervention_km ?? 0, r.total_km ?? 0],
          itemStyle: { color: shareToColor(r.low_stress_share), opacity: 0.75 },
        })),
      },
    ],
  });
  chart.off("click");
  chart.on("click", (p) => onItemActivate(items[p.dataIndex], level));
}

function onItemActivate(row, level) {
  if (!row) return;
  if (level === "regione") goRegione(row.area);
  else if (level === "provincia") goProvincia(row.regione, row.area);
  else goComune(row.istat_code);
}

// --- Level view: sortable/filterable table --------------------------------

function levelColumns(level) {
  const common = [
    { key: "superficie_km2", label: t("statsColSuperficie"), format: fmtKm2 },
    { key: "popolazione", label: t("statsColPopolazione"), format: (v) => fmtInt(v) },
    { key: "total_km", label: t("statsColKmRete"), format: fmtKm },
    { key: "low_stress_km", label: t("statsColKmBassoStress"), format: fmtKm },
    { key: "low_stress_share", label: t("statsColQuota"), format: fmtPercent },
    { key: "km_per_km2", label: t("statsColKmPerKm2"), compute: density, format: (v) => v.toFixed(2) },
    { key: "km_per_1000_ab", label: t("statsColKmPer1000Ab"), compute: perCapita, format: (v) => v.toFixed(2) },
    { key: "priority_intervention_km", label: t("statsColKmPrioritari"), format: fmtKm },
    { key: "separated_path_km", label: t("statsColKmSeparate"), format: fmtKm },
  ];
  if (level === "comune") {
    return [
      { key: "comune", label: t("statsColComune"), isName: true },
      { key: "provincia", label: t("statsColProvincia"), isText: true },
      { key: "regione", label: t("statsColRegione"), isText: true },
      ...common,
    ];
  }
  const coverageCol = { key: "coverage_pct", label: t("statsColCopertura"), format: (v, r) => t("statsCoverageValueTemplate")(fmtInt(r.comuni_processed), fmtInt(r.comuni_total), v ?? 0) };
  if (level === "provincia") {
    return [
      { key: "area", label: t("statsColProvincia"), isName: true },
      { key: "regione", label: t("statsColRegione"), isText: true },
      ...common,
      coverageCol,
    ];
  }
  return [
    { key: "area", label: t("statsColRegione"), isName: true },
    ...common,
    coverageCol,
  ];
}

// Shared 20-rows-per-page control for both the level table and the
// per-comune street table - a comune/provincia/regione list or a street
// list can run into the hundreds, and rendering (and scrolling through)
// all of it at once makes the page unreadable.
const PAGE_SIZE = 20;
function renderPager(containerId, page, totalPages, onChange) {
  const el = document.getElementById(containerId);
  el.innerHTML = "";
  if (totalPages <= 1) return;
  const prev = document.createElement("button");
  prev.type = "button";
  prev.textContent = "‹";
  prev.disabled = page <= 1;
  prev.addEventListener("click", () => onChange(page - 1));
  const label = document.createElement("span");
  label.textContent = `${page} / ${totalPages}`;
  const next = document.createElement("button");
  next.type = "button";
  next.textContent = "›";
  next.disabled = page >= totalPages;
  next.addEventListener("click", () => onChange(page + 1));
  el.append(prev, label, next);
}

function renderTable(root, items, level) {
  const wrap = document.createElement("div");
  wrap.className = "card-panel";
  const columns = levelColumns(level);
  wrap.innerHTML = `
    <div id="filters-row">
      <input type="text" id="table-filter" placeholder="${t("statsTableFilterPlaceholder")}" />
      <label style="display:flex;align-items:center;gap:6px;font-size:12px;color:#555">
        <input type="checkbox" id="table-select-all" /> ${t("statsTableSelectAllLabel")}
      </label>
    </div>
    <div class="table-wrap">
      <table class="data-table">
        <thead><tr id="table-head"></tr></thead>
        <tbody id="table-body"></tbody>
      </table>
    </div>
    <div id="table-pager" class="pager"></div>
  `;
  root.appendChild(wrap);

  let sortKey = columns.find((c) => c.key === "low_stress_share") ? "low_stress_share" : columns[0].key;
  let sortAsc = false;
  let filterText = "";
  let page = 1;

  function sortValue(row, key) {
    const col = columns.find((c) => c.key === key);
    return col && col.compute ? col.compute(row) : row[key];
  }

  function renderHead() {
    const row = document.getElementById("table-head");
    row.innerHTML = "";
    const checkTh = document.createElement("th");
    checkTh.className = "col-check";
    checkTh.textContent = "";
    row.appendChild(checkTh);
    for (const col of columns) {
      const th = document.createElement("th");
      th.textContent = col.label;
      if (col.isName || col.isText) th.classList.add("col-text");
      if (col.key === sortKey) {
        th.classList.add("sorted");
        th.setAttribute("data-arrow", sortAsc ? "▲" : "▼");
      }
      row.appendChild(th);
    }
  }
  // Sort-toggle click handlers, attached separately from renderHead()
  // (rather than inline via addEventListener there) so a re-render of
  // the head - which rebuilds every <th> from scratch - never leaves a
  // stale listener from the previous render also firing.
  function attachHeadHandlers() {
    document.querySelectorAll("#table-head th:not(.col-check)").forEach((th, i) => {
      th.onclick = () => {
        const col = columns[i];
        if (sortKey === col.key) sortAsc = !sortAsc;
        else { sortKey = col.key; sortAsc = false; }
        page = 1;
        renderHead();
        attachHeadHandlers();
        renderBody();
      };
    });
  }

  function renderBody() {
    const tbody = document.getElementById("table-body");
    tbody.innerHTML = "";
    let rows = items.filter((r) => itemName(r, level).toLowerCase().includes(filterText));
    rows.sort((a, b) => {
      const av = sortValue(a, sortKey), bv = sortValue(b, sortKey);
      let cmp;
      if (typeof av === "string" || typeof bv === "string") cmp = String(av ?? "").localeCompare(String(bv ?? ""));
      else cmp = (av ?? -Infinity) - (bv ?? -Infinity);
      return sortAsc ? cmp : -cmp;
    });
    const totalPages = Math.max(1, Math.ceil(rows.length / PAGE_SIZE));
    page = Math.min(page, totalPages);
    const pageRows = rows.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
    renderPager("table-pager", page, totalPages, (p) => {
      page = p;
      renderBody();
    });
    for (const row of pageRows) {
      const tr = document.createElement("tr");
      const key = itemKey(row, level);
      const checkTd = document.createElement("td");
      checkTd.className = "col-check";
      const checkbox = document.createElement("input");
      checkbox.type = "checkbox";
      checkbox.checked = state.compare.level === level && state.compare.items.has(key);
      checkbox.addEventListener("click", (e) => {
        e.stopPropagation();
        toggleCompare(level, key, itemName(row, level), row);
      });
      checkTd.appendChild(checkbox);
      tr.appendChild(checkTd);

      columns.forEach((col) => {
        const td = document.createElement("td");
        if (col.isName || col.isText) td.classList.add("col-text");
        if (col.isName) {
          const badges = row.capoluogo_regione
            ? `<span class="badge">${t("statsBadgeCapoluogoRegione")}</span>`
            : row.capoluogo_provincia
            ? `<span class="badge">${t("statsBadgeCapoluogoProvincia")}</span>`
            : "";
          td.innerHTML = `<span class="row-name">${row[col.key]}</span>${badges}`;
        } else {
          const raw = col.compute ? col.compute(row) : row[col.key];
          td.textContent = col.format ? col.format(raw, row) : raw ?? "-";
        }
        tr.appendChild(td);
      });
      tr.addEventListener("click", () => onItemActivate(row, level));
      tbody.appendChild(tr);
    }
  }

  document.getElementById("table-filter").addEventListener("input", (e) => {
    filterText = e.target.value.trim().toLowerCase();
    page = 1;
    renderBody();
  });
  document.getElementById("table-select-all").addEventListener("change", (e) => {
    const rows = items.filter((r) => itemName(r, level).toLowerCase().includes(filterText));
    if (e.target.checked) rows.forEach((r) => addToCompare(level, itemKey(r, level), itemName(r, level), r));
    else rows.forEach((r) => removeFromCompare(itemKey(r, level)));
    renderBody();
  });

  renderHead();
  attachHeadHandlers();
  renderBody();
}

// --- Comune detail -----------------------------------------------------

// --- Embedded priority-interventions map (comune detail only) --------------
//
// maplibre-gl/pmtiles are loaded on demand (same loadScriptOnce pattern
// app.js uses for turf/jspdf/ngraph) rather than unconditionally in
// <head>, since most visits to this page never open a comune detail at
// all - loading a ~250KB map library for a page that's mostly charts and
// tables would be wasted weight on every other view.
const scriptLoadPromises = new Map();
function loadScriptOnce(src) {
  if (!scriptLoadPromises.has(src)) {
    scriptLoadPromises.set(src, new Promise((resolve, reject) => {
      const script = document.createElement("script");
      script.src = src;
      script.onload = () => resolve();
      script.onerror = () => {
        scriptLoadPromises.delete(src);
        reject(new Error(`Failed to load script: ${src}`));
      };
      document.head.appendChild(script);
    }));
  }
  return scriptLoadPromises.get(src);
}
let maplibreLoadPromise = null;
function ensureMaplibreLoaded() {
  if (window.maplibregl && window.pmtiles) return Promise.resolve();
  if (!maplibreLoadPromise) {
    if (!document.getElementById("maplibre-css")) {
      const link = document.createElement("link");
      link.id = "maplibre-css";
      link.rel = "stylesheet";
      link.href = "../assets/vendor/maplibre-gl-5.24.0.css";
      document.head.appendChild(link);
    }
    maplibreLoadPromise = Promise.all([
      loadScriptOnce("../assets/vendor/maplibre-gl-5.24.0.js"),
      loadScriptOnce("../assets/vendor/pmtiles-4.5.0.js"),
    ]);
  }
  return maplibreLoadPromise;
}

let comuniIndexPromise = null;
function loadComuniIndex() {
  if (!comuniIndexPromise) comuniIndexPromise = loadJson("../data/comuni_index.json");
  return comuniIndexPromise;
}

let pmtilesProtocol = null;
let priorityMapInstance = null;
// True once the map itself is initialized enough to call setFilter/
// fitBounds on it - reset per comune. A row click that lands before this
// flips just queues the request instead of erroring on a half-built map.
let priorityMapReady = false;
let pendingFocusStreetName = null;
let pendingFocusStreetBbox = null;

// This map shows ONLY the priority-intervention streets (is_gap_edge,
// excluding has_parallel_cycleway) - not the comune's whole road network
// - per the user's own correction: a full LTS-colored base layer buried
// the actual point of the map. Streets are colored by their own LTS
// (almost always 3/4 - is_gap_edge edges are by definition high-stress).
// Clicking a row in the streets table below (renderInterventions'
// renderRows) calls focusPriorityStreet(), which re-filters the
// "priority-selected" layers to just that street and fits the map to it
// - same dark-case/yellow highlight app.js uses for its own single
// manually-selected gap street (GAP_SELECTION_COLOR/
// GAP_SELECTION_CASE_COLOR), applied here to whichever street was
// clicked instead of "all of them at once" (an earlier version of this
// map did that; the user asked for selection-driven highlighting tied to
// the table instead).
const PRIORITY_SELECTED_CASE_COLOR = "#1A1A1A";
const PRIORITY_SELECTED_COLOR = "#FFD60A";
// Matches no real feature (an empty `name` never appears - unnamed gap
// edges are filtered out before this map's source data is even queried
// for the table), so both selection layers start invisible until a
// street is actually clicked.
const NO_STREET_FILTER = ["==", ["get", "name"], ""];

function renderPriorityMapLegend(container) {
  const items = ["3", "4"].map(
    (cls) => `<span><span class="legend-swatch" style="background:${LTS_COLORS[cls]}"></span>${ltsLabel(cls)}</span>`
  );
  items.push(`<span class="legend-highlight"><span class="legend-swatch"></span>${t("statsPriorityMapSelectedLegend")}</span>`);
  container.innerHTML = items.join("");
}

// Called from renderInterventions' table rows and the top-10 chart.
// Re-filters the selection layers to just this street and fits the map
// to its `bbox` - precomputed server-side (build_comuni_interventions.py,
// [minlon, minlat, maxlon, maxlat]) rather than found by querying the
// map's already-loaded vector tiles at the CURRENT view/zoom
// (map.querySourceFeatures), which is what an earlier version of this
// did. That broke silently for most streets: the map's initial view
// spans the whole comune, at a zoom where tippecanoe's own tiling only
// includes major roads (see pmtiles_edges_service.py's module docstring
// on the "any zoom>=12" filter) - a residential gap-edge street simply
// isn't in ANY tile loaded yet at that zoom, so the query found nothing
// and the map just didn't move. Only the top-10-by-length chart's
// entries (skewed toward bigger, more prominent streets that DO show at
// low zoom) happened to work, which is exactly the "only the ones in the
// bar chart" symptom reported. A precomputed bbox sidesteps the whole
// loaded-tiles/zoom dependency.
function focusPriorityStreet(name, bbox) {
  if (!priorityMapInstance || !priorityMapReady) {
    pendingFocusStreetName = name;
    pendingFocusStreetBbox = bbox;
    return;
  }
  const map = priorityMapInstance;
  const filter = ["==", ["get", "name"], name];
  if (map.getLayer("priority-selected-case")) map.setFilter("priority-selected-case", filter);
  if (map.getLayer("priority-selected")) map.setFilter("priority-selected", filter);

  if (bbox) {
    map.fitBounds(
      [
        [bbox[0], bbox[1]],
        [bbox[2], bbox[3]],
      ],
      { padding: 60, maxZoom: 17 }
    );
    return;
  }
  // Fallback for an interventions JSON generated before bbox was added -
  // best-effort, only works if the street happens to already be in a
  // loaded tile (see comment above).
  const features = map.querySourceFeatures("lts", { sourceLayer: "lts", filter });
  if (!features.length) return;
  const bounds = new window.maplibregl.LngLatBounds();
  for (const feature of features) {
    const geom = feature.geometry;
    const lines = geom.type === "MultiLineString" ? geom.coordinates : [geom.coordinates];
    for (const line of lines) for (const coord of line) bounds.extend(coord);
  }
  map.fitBounds(bounds, { padding: 60, maxZoom: 17 });
}

async function renderPriorityMap(comune) {
  priorityMapReady = false;
  pendingFocusStreetName = null;
  pendingFocusStreetBbox = null;
  const mapPanel = document.getElementById("priority-map-panel");
  if (!mapPanel) return; // user already navigated away while this was loading
  const container = document.getElementById("priority-map");
  const legend = document.getElementById("priority-map-legend");

  if (priorityMapInstance) {
    priorityMapInstance.remove();
    priorityMapInstance = null;
  }

  let comuniIndex, maplibregl, pmtiles;
  try {
    [comuniIndex] = await Promise.all([loadComuniIndex(), ensureMaplibreLoaded()]);
    ({ maplibregl } = window);
    ({ pmtiles } = window);
  } catch (error) {
    container.innerHTML = `<p>${t("statsInterventionsUnavailable")}</p>`;
    return;
  }
  // The panel may have been torn down (user navigated to another comune)
  // while the awaits above were in flight - bail rather than initializing
  // a map into a detached container.
  if (!document.getElementById("priority-map-panel")) return;

  const indexEntry = comuniIndex.find((e) => e.istat === comune.istat_code);
  if (!indexEntry) {
    container.innerHTML = `<p>${t("statsInterventionsUnavailable")}</p>`;
    return;
  }

  if (!pmtilesProtocol) {
    pmtilesProtocol = new pmtiles.Protocol();
    maplibregl.addProtocol("pmtiles", pmtilesProtocol.tile);
  }
  const slug = indexEntry.slug;
  const pmtilesHref = new URL(`../data/${slug}_lts.pmtiles`, window.location.href).toString();
  const tiles = new pmtiles.PMTiles(pmtilesHref);
  pmtilesProtocol.add(tiles);

  const map = new maplibregl.Map({
    container: "priority-map",
    style: "https://styles.maptoolkit.org/light.json",
    bounds: indexEntry.bbox,
    fitBoundsOptions: { padding: 20 },
  });
  priorityMapInstance = map;
  map.addControl(new maplibregl.NavigationControl({ showCompass: false }), "top-right");

  map.on("load", () => {
    if (priorityMapInstance !== map) return; // superseded by a later comune before tiles finished loading
    map.addSource("lts", { type: "vector", url: `pmtiles://${pmtilesHref}` });

    // Only priority-intervention edges are drawn at all (is_gap_edge,
    // excluding has_parallel_cycleway) - unnamed ones included here even
    // though they don't get a row in the table below (no name to list/
    // click), so the map still shows the full picture of what's flagged.
    const priorityFilter = ["all", ["==", ["to-string", ["get", "is_gap_edge"]], "true"], ["!=", ["to-string", ["get", "has_parallel_cycleway"]], "true"]];
    map.addLayer({
      id: "priority-only-lines",
      type: "line",
      source: "lts",
      "source-layer": "lts",
      filter: priorityFilter,
      layout: { "line-join": "round", "line-cap": "round" },
      paint: {
        "line-color": ["match", ["to-string", ["get", "lts"]], "1", LTS_COLORS["1"], "2", LTS_COLORS["2"], "3", LTS_COLORS["3"], "4", LTS_COLORS["4"], LTS_COLORS["0"]],
        "line-width": ["interpolate", ["linear"], ["zoom"], 10, 1.5, 16, 4],
      },
    });
    // Selection layers: invisible (NO_STREET_FILTER) until a table row
    // is clicked (focusPriorityStreet), added after priority-only-lines
    // so they always draw on top of it.
    map.addLayer({
      id: "priority-selected-case",
      type: "line",
      source: "lts",
      "source-layer": "lts",
      filter: NO_STREET_FILTER,
      layout: { "line-join": "round", "line-cap": "round" },
      paint: { "line-color": PRIORITY_SELECTED_CASE_COLOR, "line-width": ["interpolate", ["linear"], ["zoom"], 10, 3, 16, 7] },
    });
    map.addLayer({
      id: "priority-selected",
      type: "line",
      source: "lts",
      "source-layer": "lts",
      filter: NO_STREET_FILTER,
      layout: { "line-join": "round", "line-cap": "round" },
      paint: { "line-color": PRIORITY_SELECTED_COLOR, "line-width": ["interpolate", ["linear"], ["zoom"], 10, 1.5, 16, 4] },
    });

    const popup = new maplibregl.Popup({ closeButton: false, maxWidth: "240px" });
    for (const layerId of ["priority-only-lines", "priority-selected"]) {
      map.on("mouseenter", layerId, () => { map.getCanvas().style.cursor = "pointer"; });
      map.on("mouseleave", layerId, () => { map.getCanvas().style.cursor = ""; popup.remove(); });
      map.on("click", layerId, (e) => {
        const props = e.features[0].properties;
        popup
          .setLngLat(e.lngLat)
          .setHTML(`<strong>${props.name || "-"}</strong><br/>LTS ${props.lts}`)
          .addTo(map);
      });
    }

    // Ready as soon as the layers exist - setFilter/fitBounds don't need
    // tiles to have actually finished loading (unlike the old
    // querySourceFeatures approach this replaced, which did and was the
    // whole reason this readiness gate existed in the first place).
    priorityMapReady = true;
    if (pendingFocusStreetName) {
      focusPriorityStreet(pendingFocusStreetName, pendingFocusStreetBbox);
      pendingFocusStreetName = null;
      pendingFocusStreetBbox = null;
    }
  });

  renderPriorityMapLegend(legend);
}

function renderComuneDetail(root, istatCode) {
  const comune = state.comuni.find((c) => c.istat_code === istatCode);
  if (!comune) {
    root.innerHTML = `<p>${t("statsComuneNotFound")}</p>`;
    return;
  }

  const badges = [
    comune.capoluogo_regione ? `<span class="badge">${t("statsBadgeCapoluogoDiRegione")}</span>` : "",
    !comune.capoluogo_regione && comune.capoluogo_provincia ? `<span class="badge">${t("statsBadgeCapoluogoDiProvincia")}</span>` : "",
  ].join("");

  const header = document.createElement("div");
  header.innerHTML = `<h2 style="margin:0 0 4px">${comune.comune}${badges}</h2>
    <p style="color:#666;margin:0 0 10px">${comune.provincia} · ${comune.regione}</p>
    <p style="margin:0 0 14px"><a class="nav-link" href="../index.html?area=${encodeURIComponent(areaSlug(comune.comune))}" target="_blank" rel="noopener">${t("statsOpenInMap")} →</a></p>`;
  root.appendChild(header);

  const kpiRow = document.createElement("div");
  kpiRow.id = "kpi-row";
  kpiRow.innerHTML = [
    [t("statsKpiSuperficie"), fmtKm2(comune.superficie_km2)],
    [t("statsKpiPopolazione"), fmtInt(comune.popolazione)],
    [t("statsKpiKmRete"), fmtKm(comune.total_km)],
    [t("statsKpiQuota"), fmtPercent(comune.low_stress_share)],
    [t("statsKpiKmPrioritario"), fmtKm(comune.priority_intervention_km)],
    [t("statsKpiKmSeparate"), fmtKm(comune.separated_path_km)],
    [t("statsKpiNonCyclable"), fmtKm(nonCyclableKm(comune))],
    [t("statsKpiIsole"), fmtInt(comune.low_stress_island_count), t("statsKpiIsoleHelp")],
  ]
    .map(
      ([label, value, help]) =>
        `<div class="kpi-card"><div class="kpi-label">${label}${help ? ` <span class="kpi-help" title="${help}">ⓘ</span>` : ""}</div><div class="kpi-value">${value}</div></div>`
    )
    .join("");
  root.appendChild(kpiRow);

  root.appendChild(buildCompareWithControl(comune));

  const grid = document.createElement("div");
  grid.className = "charts-grid";
  grid.innerHTML = `
    <div class="card-panel">
      <h2>${t("statsComuneLtsTitle")}</h2>
      <div id="chart-comune-lts" class="chart-box" style="height:230px"></div>
    </div>
    <div class="card-panel">
      <h2>${t("statsChartExcludedTitle")}</h2>
      <p class="chart-note">${t("statsChartExcludedNote")}</p>
      <div id="chart-comune-excluded" class="chart-box" style="height:230px"></div>
    </div>
  `;
  root.appendChild(grid);

  const ltsChart = getChart("chart-comune-lts");
  applyChartOption(ltsChart, {
    grid: { left: 10, right: 40, top: 45, bottom: 60 },
    xAxis: { type: "value", position: "top", axisLabel: { formatter: (v) => `${v} km` } },
    yAxis: { type: "category", data: [comune.comune], axisLabel: { show: false } },
    tooltip: { trigger: "item" },
    series: ["0", "1", "2", "3", "4"].map((cls) => ({
      name: ltsLabel(cls),
      type: "bar",
      stack: "lts",
      itemStyle: { color: LTS_COLORS[cls] },
      data: [(comune.km_by_lts && comune.km_by_lts[cls]) || 0],
    })),
    legend: { bottom: 0, left: "center", textStyle: { fontSize: 10 } },
  });

  const exclChart = getChart("chart-comune-excluded");
  applyChartOption(exclChart, {
    grid: { left: 10, right: 40, top: 45, bottom: 60 },
    xAxis: { type: "value", position: "top", axisLabel: { formatter: (v) => `${v} km` } },
    yAxis: { type: "category", data: [comune.comune], axisLabel: { show: false } },
    tooltip: { trigger: "item" },
    series: excludedFields().map((f) => ({
      name: f.label,
      type: "bar",
      stack: "excl",
      itemStyle: { color: f.color },
      data: [f.value(comune)],
    })),
    legend: { bottom: 0, left: "center", textStyle: { fontSize: 10 } },
  });

  const interventionsPanel = document.createElement("div");
  interventionsPanel.className = "card-panel";
  interventionsPanel.innerHTML = `<h2>${t("statsInterventionsTitle")}</h2><p class="chart-note">${t("statsInterventionsLoading")}</p>`;
  root.appendChild(interventionsPanel);

  loadJson(`../data/interventions/${istatCode}.json`)
    .then((data) => renderInterventions(interventionsPanel, data))
    .catch(() => {
      interventionsPanel.innerHTML = `<h2>${t("statsInterventionsTitle")}</h2><p>${t("statsInterventionsUnavailable")}</p>`;
    });

  // Placed after the interventions panel (not before it) so the map
  // that visualizes "Vie con interventi prioritari" reads as a follow-up
  // to that list, not a preview of it - the user's own ordering.
  const mapPanel = document.createElement("div");
  mapPanel.className = "card-panel";
  mapPanel.id = "priority-map-panel";
  mapPanel.innerHTML = `
    <h2>${t("statsPriorityMapTitle")}</h2>
    <p class="chart-note">${t("statsPriorityMapNote")}</p>
    <div id="priority-map"></div>
    <div id="priority-map-legend"></div>
  `;
  root.appendChild(mapPanel);
  renderPriorityMap(comune);
}

function renderInterventions(panel, data) {
  const streets = data.streets || [];
  const highwayKm = data.highway_km || {};

  panel.innerHTML = `
    <h2>${t("statsHighwayCompositionTitle")}</h2>
    <p class="chart-note">${t("statsHighwayCompositionNote")}</p>
    <div id="chart-highway" class="chart-box" style="height:${Math.max(160, Object.keys(highwayKm).length * 24)}px"></div>
    <h2 style="margin-top:20px">${t("statsInterventionsTitle")}</h2>
    <p class="chart-note">${t("statsPriorityStreetsNote")}</p>
    ${streets.length ? `<p class="chart-note">${t("statsPriorityChartCaptionTemplate")(Math.min(streets.length, 10), streets.length)}</p>` : ""}
    ${streets.length ? `<div id="chart-streets" class="chart-box" style="height:${Math.min(streets.length, 10) * 28 + 40}px"></div>` : `<p>${t("statsNoNamedStreets")}</p>`}
    ${streets.length ? `
    <div id="filters-row" style="margin-top:14px">
      <input type="text" id="street-filter" placeholder="${t("statsStreetFilterPlaceholder")}" />
    </div>
    <div class="table-wrap">
      <table class="data-table" id="streets-table">
        <thead><tr>
          <th data-key="name">${t("statsColVia")}</th>
          <th data-key="lts">${t("statsColLts")}</th>
          <th data-key="centrality">${t("statsColCentralita")}</th>
          <th data-key="length_km">${t("statsColKm")}</th>
          <th data-key="edge_count">${t("statsColNTratti")}</th>
          <th data-key="highway">${t("statsColTipo")}</th>
        </tr></thead>
        <tbody id="streets-body"></tbody>
      </table>
    </div>
    <div id="streets-pager" class="pager"></div>` : ""}
  `;

  const highwayEntries = Object.entries(highwayKm).sort((a, b) => b[1] - a[1]);
  const highwayChart = getChart("chart-highway");
  const layoutH = hbarLayout();
  applyChartOption(
    highwayChart,
    {
      grid: { left: layoutH.left, right: 50, top: 10, bottom: 20 },
      xAxis: { type: "value", axisLabel: { formatter: (v) => `${v} km`, hideOverlap: true } },
      yAxis: { type: "category", data: highwayEntries.map(([k]) => highwayLabel(k)).reverse(), axisLabel: { width: layoutH.labelWidth, overflow: "truncate" } },
      series: [{ type: "bar", data: highwayEntries.map(([, v]) => v).reverse(), itemStyle: { color: "#3B4A7A" }, barMaxWidth: 18 }],
    },
    { dataZoom: true }
  );

  if (!streets.length) return;

  const top10 = streets.slice(0, 10);
  const streetsChart = getChart("chart-streets");
  const layoutS = hbarLayout();
  applyChartOption(streetsChart, {
    grid: { left: layoutS.left, right: 40, top: 10, bottom: 20 },
    xAxis: { type: "value", axisLabel: { formatter: (v) => `${v} km`, hideOverlap: true } },
    yAxis: { type: "category", data: top10.map((s) => s.name).reverse(), axisLabel: { width: layoutS.labelWidth, overflow: "truncate" } },
    tooltip: { formatter: (p) => t("statsStreetTooltipTemplate")(p.name, top10[top10.length - 1 - p.dataIndex].lts, fmtKm(p.value)) },
    series: [
      {
        type: "bar",
        data: top10.map((s) => ({ value: s.length_km, itemStyle: { color: LTS_COLORS[String(s.lts)] } })).reverse(),
        barMaxWidth: 18,
      },
    ],
  });
  streetsChart.off("click");
  streetsChart.on("click", (p) => {
    const street = top10[top10.length - 1 - p.dataIndex];
    focusPriorityStreet(street.name, street.bbox);
    document.getElementById("priority-map-panel")?.scrollIntoView({ behavior: "smooth", block: "nearest" });
  });

  let sortKey = "lts", sortAsc = false, filterText = "", streetsPage = 1;
  function renderRows() {
    const tbody = document.getElementById("streets-body");
    tbody.innerHTML = "";
    let rows = streets.filter((s) => s.name.toLowerCase().includes(filterText));
    rows.sort((a, b) => {
      const av = a[sortKey], bv = b[sortKey];
      let cmp = typeof av === "string" ? String(av).localeCompare(String(bv)) : (av ?? 0) - (bv ?? 0);
      return sortAsc ? cmp : -cmp;
    });
    const totalPages = Math.max(1, Math.ceil(rows.length / PAGE_SIZE));
    streetsPage = Math.min(streetsPage, totalPages);
    const pageRows = rows.slice((streetsPage - 1) * PAGE_SIZE, streetsPage * PAGE_SIZE);
    renderPager("streets-pager", streetsPage, totalPages, (p) => {
      streetsPage = p;
      renderRows();
    });
    for (const s of pageRows) {
      const tr = document.createElement("tr");
      tr.innerHTML = `
        <td class="row-name">${s.name}</td>
        <td><span class="street-lts-badge" style="background:${LTS_COLORS[String(s.lts)]}">${s.lts}</span></td>
        <td>${centralityLabel(s.centrality_class)}</td>
        <td>${fmtKm(s.length_km)}</td>
        <td>${fmtInt(s.edge_count)}</td>
        <td>${highwayLabel(s.highway)}</td>
      `;
      tr.style.cursor = "pointer";
      tr.title = t("statsPriorityMapZoomHint");
      tr.addEventListener("click", () => {
        focusPriorityStreet(s.name, s.bbox);
        const mapPanel = document.getElementById("priority-map-panel");
        if (mapPanel) mapPanel.scrollIntoView({ behavior: "smooth", block: "nearest" });
      });
      tbody.appendChild(tr);
    }
  }
  document.querySelectorAll("#streets-table th").forEach((th) => {
    th.addEventListener("click", () => {
      const key = th.dataset.key;
      if (sortKey === key) sortAsc = !sortAsc;
      else { sortKey = key; sortAsc = false; }
      streetsPage = 1;
      renderRows();
    });
  });
  document.getElementById("street-filter").addEventListener("input", (e) => {
    filterText = e.target.value.trim().toLowerCase();
    streetsPage = 1;
    renderRows();
  });
  renderRows();
}

// --- "Confronta con" (comune detail page) ---------------------------------
//
// The direct route into the compare modal from a single comune's own
// page - approved mockup (see this feature's own design review):
// https://claude.ai/code/artifact/8cfe4623-986d-4d06-b888-c0adf8f8a9bc.
// Reuses the exact addToCompare/openCompareModal machinery the
// checkbox-table compare (setupSort's row checkboxes, elsewhere in this
// file) already relies on - this is only a friendlier way to reach it
// than "go back to a list, tick two boxes". Rebuilt fresh on every
// renderComuneDetail() call (own DOM, not reused across comuni) so
// `comune` is always the one currently on screen, never a stale closure
// from a previous drill-down.
function buildCompareWithControl(comune) {
  const wrap = document.createElement("div");
  wrap.className = "compare-with-row";
  wrap.innerHTML = `
    <label class="compare-with-label" for="compare-with-input">${t("statsCompareWithLabel")}</label>
    <div class="compare-with-input-wrap">
      <input type="text" id="compare-with-input" autocomplete="off" placeholder="${t("statsSearchPlaceholder")}">
      <div class="compare-with-results hidden"></div>
    </div>
  `;
  const input = wrap.querySelector("#compare-with-input");
  const results = wrap.querySelector(".compare-with-results");

  const pickComune = (other) => {
    addToCompare("comune", comune.istat_code, comune.comune, comune);
    addToCompare("comune", other.istat_code, other.comune, other);
    input.value = "";
    results.classList.add("hidden");
    openCompareModal();
  };

  input.addEventListener("input", () => {
    const q = input.value.trim().toLowerCase();
    if (q.length < 2) {
      results.classList.add("hidden");
      return;
    }
    const matches = state.comuni
      .filter((c) => c.istat_code !== comune.istat_code && c.comune.toLowerCase().includes(q))
      .slice(0, 8);
    if (!matches.length) {
      results.innerHTML = `<div class="compare-with-empty">${t("statsSearchNoResults")}</div>`;
      results.classList.remove("hidden");
      return;
    }
    results.innerHTML = matches
      .map((c, i) => `<div data-idx="${i}"><strong>${c.comune}</strong> <span class="sr-meta">${c.provincia} · ${c.regione}</span></div>`)
      .join("");
    results.classList.remove("hidden");
    results.querySelectorAll("div[data-idx]").forEach((div) => {
      div.addEventListener("click", () => pickComune(matches[Number(div.dataset.idx)]));
    });
  });
  input.addEventListener("keydown", (e) => {
    if (e.key !== "Enter") return;
    const first = results.querySelector("div[data-idx]");
    if (first) first.click();
  });
  // blur-with-delay, not a document-level click listener: this control
  // is rebuilt on every comune drill-down (unlike setupSearch's, which
  // is wired once at page load) - a document listener added here would
  // accumulate a new one per visit and never get removed.
  input.addEventListener("blur", () => {
    window.setTimeout(() => results.classList.add("hidden"), 150);
  });

  return wrap;
}

// --- Search box ----------------------------------------------------------

function setupSearch() {
  const input = document.getElementById("comune-search");
  const results = document.getElementById("search-results");
  input.addEventListener("input", () => {
    const q = input.value.trim().toLowerCase();
    if (q.length < 2) {
      results.classList.add("hidden");
      return;
    }
    const matches = state.comuni.filter((c) => c.comune.toLowerCase().includes(q)).slice(0, 15);
    if (!matches.length) {
      results.innerHTML = `<div>${t("statsSearchNoResults")}</div>`;
      results.classList.remove("hidden");
      return;
    }
    results.innerHTML = matches
      .map(
        (c, i) =>
          `<div data-idx="${i}"><strong>${c.comune}</strong> <span class="sr-meta">${c.provincia} · ${c.regione}</span></div>`
      )
      .join("");
    results.classList.remove("hidden");
    results.querySelectorAll("div[data-idx]").forEach((div) => {
      div.addEventListener("click", () => {
        const c = matches[Number(div.dataset.idx)];
        input.value = "";
        results.classList.add("hidden");
        goComune(c.istat_code);
      });
    });
  });
  document.addEventListener("click", (e) => {
    if (!e.target.closest("#search-wrap")) results.classList.add("hidden");
  });
}

// --- Compare tray + modal --------------------------------------------------

function toggleCompare(level, key, name, row) {
  if (state.compare.items.has(key)) removeFromCompare(key);
  else addToCompare(level, key, name, row);
}

function addToCompare(level, key, name, row) {
  if (state.compare.level && state.compare.level !== level) {
    state.compare.items.clear();
  }
  state.compare.level = level;
  state.compare.items.set(key, { name, row });
  renderCompareTray();
}

function removeFromCompare(key) {
  state.compare.items.delete(key);
  if (!state.compare.items.size) state.compare.level = null;
  renderCompareTray();
}

// --- Share bar (always-visible copy-link + socials) ------------------------
//
// Reuses the exact URL builders and inline-SVG icons web/app.js's own
// ShareControl modal uses (same brand colors, same platforms) for visual
// consistency, but as a persistent fixed bar rather than a toggled
// panel, and pointed at THIS page's own URL (kept in sync with the
// current drill-down by syncUrlState) - no need for app.js's compact
// base64 ?c= encoding here, since this page's shareable state is just
// three plain, readable query params.
const SOCIAL_SHARE_URL_BUILDERS = {
  facebook: (url) => `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`,
  linkedin: (url) => `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`,
  x: (url, text) => `https://twitter.com/intent/tweet?url=${encodeURIComponent(url)}&text=${encodeURIComponent(text)}`,
  whatsapp: (url, text) => `https://wa.me/?text=${encodeURIComponent(`${text} ${url}`)}`,
};

function setupShareBar() {
  document.getElementById("share-copy-link").addEventListener("click", async (e) => {
    const url = window.location.href;
    try {
      await navigator.clipboard.writeText(url);
      const btn = e.currentTarget;
      const original = btn.title;
      btn.title = t("shareCopied");
      setTimeout(() => { btn.title = original; }, 1500);
    } catch (error) {
      window.prompt(t("statsShareCopyFallback"), url);
    }
  });
}

function renderShareBar() {
  const url = window.location.href;
  const text = t("shareIntentText");
  document.getElementById("share-social-facebook").href = SOCIAL_SHARE_URL_BUILDERS.facebook(url);
  document.getElementById("share-social-linkedin").href = SOCIAL_SHARE_URL_BUILDERS.linkedin(url);
  document.getElementById("share-social-x").href = SOCIAL_SHARE_URL_BUILDERS.x(url, text);
  document.getElementById("share-social-whatsapp").href = SOCIAL_SHARE_URL_BUILDERS.whatsapp(url, text);
}

function setupCompareTray() {
  document.getElementById("compare-clear").addEventListener("click", () => {
    state.compare.items.clear();
    state.compare.level = null;
    renderCompareTray();
    render();
  });
  document.getElementById("compare-open").addEventListener("click", openCompareModal);
  document.getElementById("compare-close").addEventListener("click", closeCompareModal);
  document.getElementById("compare-modal-backdrop").addEventListener("click", (e) => {
    if (e.target.id === "compare-modal-backdrop") closeCompareModal();
  });
}

function compareLevelLabel() {
  return { regione: t("statsCompareLevelRegioni"), provincia: t("statsCompareLevelProvince"), comune: t("statsCompareLevelComuni") }[state.compare.level];
}

function renderCompareTray() {
  const tray = document.getElementById("compare-tray");
  document.body.classList.toggle("compare-active", state.compare.items.size > 0);
  document.getElementById("compare-open").textContent = t("statsCompareButton");
  document.getElementById("compare-clear").textContent = t("statsCompareClear");
  if (!state.compare.items.size) {
    tray.classList.add("hidden");
    return;
  }
  tray.classList.remove("hidden");
  document.getElementById("compare-label").textContent = t("statsCompareLabelTemplate")(compareLevelLabel());
  const chips = document.getElementById("compare-chips");
  chips.innerHTML = "";
  for (const [key, { name }] of state.compare.items) {
    const chip = document.createElement("span");
    chip.className = "compare-chip";
    chip.textContent = name + " ✕";
    chip.style.cursor = "pointer";
    chip.addEventListener("click", () => {
      removeFromCompare(key);
      render();
    });
    chips.appendChild(chip);
  }
  document.getElementById("compare-open").disabled = state.compare.items.size < 2;
}

function openCompareModal() {
  if (state.compare.items.size < 2) return;
  const rows = [...state.compare.items.values()].map((v) => v.row);
  const level = state.compare.level;
  document.getElementById("compare-modal-title").textContent = t("statsCompareModalTitleTemplate")(compareLevelLabel());
  const body = document.getElementById("compare-modal-body");
  // KPI table first, charts below - same fields as #kpi-row on a
  // comune's own page (present at regione/provincia level too, see
  // scripts/build_regional_stats.py's own SUMMARY_FIELDS), so the raw
  // numbers are readable before anyone has to interpret a bar.
  body.innerHTML = `
    <table id="compare-kpi-table">
      <thead><tr><th></th>${rows.map((r) => `<th>${itemName(r, level)}</th>`).join("")}</tr></thead>
      <tbody>
        <tr><td>${t("statsKpiPopolazione")}</td>${rows.map((r) => `<td>${fmtInt(r.popolazione)}</td>`).join("")}</tr>
        <tr><td>${t("statsKpiSuperficie")}</td>${rows.map((r) => `<td>${fmtKm2(r.superficie_km2)}</td>`).join("")}</tr>
        <tr><td>${t("statsKpiKmRete")}</td>${rows.map((r) => `<td>${fmtKm(r.total_km)}</td>`).join("")}</tr>
        <tr><td>${t("statsKpiKmPrioritario")}</td>${rows.map((r) => `<td>${fmtKm(r.priority_intervention_km)}</td>`).join("")}</tr>
      </tbody>
    </table>
    <div id="chart-compare-share" class="chart-box" style="height:${Math.max(160, rows.length * 34)}px"></div>
    <div id="chart-compare-lts" class="chart-box" style="height:${Math.max(160, rows.length * 34)}px;margin-top:20px"></div>
  `;
  document.getElementById("compare-modal-backdrop").classList.remove("hidden");

  const shareChart = getChart("chart-compare-share");
  applyChartOption(shareChart, {
    title: { text: t("statsCompareShareChartTitle"), left: "center", textStyle: { fontSize: 13 } },
    grid: { left: 140, right: 40, top: 40, bottom: 20 },
    xAxis: { type: "value", max: 1, axisLabel: { formatter: (v) => `${Math.round(v * 100)}%` } },
    yAxis: { type: "category", data: rows.map((r) => itemName(r, level)) },
    series: [{ type: "bar", data: rows.map((r) => ({ value: r.low_stress_share ?? 0, itemStyle: { color: shareToColor(r.low_stress_share) } })), barMaxWidth: 22 }],
  });

  const ltsChart = getChart("chart-compare-lts");
  applyChartOption(ltsChart, {
    title: { text: t("statsCompareLtsChartTitle"), left: "center", textStyle: { fontSize: 13 } },
    grid: { left: 140, right: 40, top: 40, bottom: 20 },
    xAxis: { type: "value", axisLabel: { formatter: (v) => `${v} km` } },
    yAxis: { type: "category", data: rows.map((r) => itemName(r, level)) },
    legend: { top: 20 },
    series: ["0", "1", "2", "3", "4"].map((cls) => ({
      name: ltsLabel(cls),
      type: "bar",
      stack: "lts",
      itemStyle: { color: LTS_COLORS[cls] },
      data: rows.map((r) => (r.km_by_lts && r.km_by_lts[cls]) || 0),
    })),
  });
}

function closeCompareModal() {
  document.getElementById("compare-modal-backdrop").classList.add("hidden");
}
