// Stats page (regione -> provincia -> comune drill-down + comparison +
// per-comune priority-intervention street list), backed by three
// national rollup files generated by scripts/build_comuni_stats.py and
// scripts/build_regional_stats.py (web/data/italia_{regione,provincia,
// comuni}_stats.json) plus one small per-comune file generated by
// scripts/build_comuni_interventions.py (web/data/interventions/
// <istat_code>.json), fetched only when that comune's detail is opened.
//
// Fully localized via I18N (i18n.js) like the rest of the site - every
// user-facing string here goes through t()/tf(), including chart titles,
// table headers and the LTS/excluded-km/highway-type labels baked into
// chart data. render() is re-run in full on a language change (see the
// lang-select handler in init()) rather than trying to patch text nodes
// in place, since almost every DOM node on this page is templated string
// HTML rebuilt from state anyway.

// Italy-wide constants used only for the coverage note - these are
// stable geographic facts (comuni/province/regioni counts), not derived
// from the partial dataset, which currently only covers a handful of
// regioni.
const ITALY_TOTAL_COMUNI = 7896;
const ITALY_TOTAL_PROVINCE = 107;
const ITALY_TOTAL_REGIONI = 20;

const LTS_COLORS = { "1": "#146C36", "2": "#A6B32C", "3": "#CC7722", "4": "#B7231F", "0": "#6B6B6B" };

function ltsLabel(cls) {
  return t(`statsLts${cls}`);
}

// "Non-cyclable" deliberately merges two different pipeline concepts into
// one chart: the four excluded_* buckets (roads dropped before LTS
// classification even runs - motorroad, mountain trail, restricted
// access, service road) AND km_by_lts["0"] (roads that reached
// classification but came out "not allowed/not applicable"). Both are km
// nobody can actually cycle on right now, which is the question this
// chart answers - the pipeline's internal distinction between "excluded"
// and "classified as 0" isn't something a comune needs to care about.
function excludedFields() {
  return [
    { key: "excluded_mountain_trail_km", label: t("statsExclMountainTrail"), color: "#5C6BC0", value: (r) => r.excluded_mountain_trail_km || 0 },
    { key: "excluded_motorroad_km", label: t("statsExclMotorroad"), color: "#8D6E63", value: (r) => r.excluded_motorroad_km || 0 },
    { key: "excluded_restricted_access_km", label: t("statsExclRestrictedAccess"), color: "#78909C", value: (r) => r.excluded_restricted_access_km || 0 },
    { key: "excluded_service_road_km", label: t("statsExclServiceRoad"), color: "#26A69A", value: (r) => r.excluded_service_road_km || 0 },
    { key: "lts0", label: t("statsExclNotAllowed"), color: LTS_COLORS["0"], value: (r) => (r.km_by_lts && r.km_by_lts["0"]) || 0 },
  ];
}
function nonCyclableKm(row) {
  return excludedFields().reduce((sum, f) => sum + f.value(row), 0);
}

// scripts/build_comuni_interventions.py names web/data/interventions/
// files by istat_code, but the main map (web/index.html) is keyed by
// name-derived slug (?area=<slug>, matching <slug>_lts.pmtiles) - mirrors
// domain/area_spec.py::slugify exactly (NFKD-normalize, drop combining
// marks, spaces to underscores, strip anything else unsafe) so the link
// always resolves to a real tileset.
function areaSlug(name) {
  return name
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/ /g, "_")
    .replace(/[^A-Za-z0-9_.-]/g, "");
}

const HIGHWAY_KEY_MAP = {
  residential: "statsHwResidential",
  living_street: "statsHwLivingStreet",
  unclassified: "statsHwUnclassified",
  tertiary: "statsHwTertiary",
  tertiary_link: "statsHwTertiaryLink",
  secondary: "statsHwSecondary",
  secondary_link: "statsHwSecondaryLink",
  primary: "statsHwPrimary",
  primary_link: "statsHwPrimaryLink",
  trunk: "statsHwTrunk",
  trunk_link: "statsHwTrunkLink",
  motorway: "statsHwMotorway",
  motorway_link: "statsHwMotorwayLink",
  service: "statsHwService",
  track: "statsHwTrack",
  path: "statsHwPath",
  footway: "statsHwFootway",
  cycleway: "statsHwCycleway",
  pedestrian: "statsHwPedestrian",
  steps: "statsHwSteps",
  bridleway: "statsHwBridleway",
  sconosciuto: "statsHwUnknown",
};

function highwayLabel(tag) {
  const key = HIGHWAY_KEY_MAP[tag];
  return key ? t(key) : tag ? tag.charAt(0).toUpperCase() + tag.slice(1) : t("statsHwOther");
}

const CENTRALITY_KEY_MAP = {
  zero: "statsCentralityZero",
  low: "statsCentralityLow",
  medium: "statsCentralityMedium",
  high: "statsCentralityHigh",
  very_high: "statsCentralityVeryHigh",
};
function centralityLabel(cls) {
  const key = CENTRALITY_KEY_MAP[cls];
  return key ? t(key) : cls ?? "-";
}

function localeForLang(lang) {
  return { it: "it-IT", en: "en-GB", de: "de-DE", fr: "fr-FR" }[lang] || "it-IT";
}
function fmtKm(v) { return v == null ? "-" : `${v.toFixed(1)} km`; }
function fmtKm2(v) { return v == null ? "-" : `${v.toFixed(1)} km²`; }
function fmtPercent(v) { return v == null ? "-" : `${Math.round(v * 100)}%`; }
function fmtInt(v) { return v == null ? "-" : Math.round(v).toLocaleString(localeForLang(currentLang())); }

// LTS0 (red) -> LTS1 (green) linear interpolation, reused so every
// share-driven color (treemap, scatter) reads consistently with the
// on-map LTS palette (low share = same alarm-red as LTS4, high share =
// the same calm green as LTS1).
function shareToColor(share) {
  const bad = [0xb7, 0x23, 0x1f];
  const good = [0x14, 0x6c, 0x36];
  const frac = Math.max(0, Math.min(1, share ?? 0));
  const mix = bad.map((c, i) => Math.round(c + (good[i] - c) * frac));
  return `rgb(${mix.join(",")})`;
}

// --- i18n ---------------------------------------------------------------

function currentLang() {
  const params = new URLSearchParams(window.location.search);
  return params.get("lang") in I18N ? params.get("lang") : "it";
}
function t(key) {
  return I18N[currentLang()][key] ?? I18N.it[key];
}

// --- Data loading -----------------------------------------------------

const state = {
  regioni: [],
  province: [],
  comuni: [],
  currentRegione: null,
  currentProvincia: null,
  currentComuneIstat: null,
  compare: { level: null, items: new Map() }, // key -> {name, row}
};

function loadJson(path) {
  return fetch(path).then((r) => {
    if (!r.ok) throw new Error(`HTTP ${r.status} on ${path}`);
    return r.json();
  });
}

Promise.all([
  loadJson("../data/italia_regione_stats.json"),
  loadJson("../data/italia_provincia_stats.json"),
  loadJson("../data/italia_comuni_stats.json"),
])
  .then(([regioni, province, comuni]) => {
    state.regioni = regioni;
    state.province = province;
    state.comuni = comuni;
    init();
  })
  .catch((error) => {
    document.getElementById("view-root").innerHTML = `<p style="color:#b7231f">${t("statsLoadErrorTemplate")(error.message)}</p>`;
  });

function init() {
  applyStaticTranslations();
  document.getElementById("lang-select").addEventListener("change", (e) => {
    const url = new URL(window.location.href);
    url.searchParams.set("lang", e.target.value);
    window.history.replaceState({}, "", url);
    applyStaticTranslations();
    render();
    renderCompareTray();
  });
  setupSearch();
  setupCompareTray();
  setupShareBar();
  restoreStateFromUrl();
  render();
}

// Deep-linking: a shared stats.js URL carries regione/provincia/comune
// (istat_code) query params, read once here before the first render so
// the page opens straight into the shared view instead of always
// starting at the Italia root. render() itself keeps these params in
// sync on every navigation (see syncUrlState below), so the address bar
// - and therefore the share bar's links - always reflect what's on
// screen, no separate "share this view" state to maintain.
function restoreStateFromUrl() {
  const params = new URLSearchParams(window.location.search);
  const comuneIstat = params.get("comune");
  const provincia = params.get("provincia");
  const regione = params.get("regione");
  if (comuneIstat && state.comuni.some((c) => c.istat_code === comuneIstat)) {
    const comune = state.comuni.find((c) => c.istat_code === comuneIstat);
    state.currentRegione = comune.regione;
    state.currentProvincia = comune.provincia;
    state.currentComuneIstat = comuneIstat;
  } else if (provincia && state.province.some((p) => p.area === provincia)) {
    state.currentRegione = state.province.find((p) => p.area === provincia).regione;
    state.currentProvincia = provincia;
  } else if (regione && state.regioni.some((r) => r.area === regione)) {
    state.currentRegione = regione;
  }
}

function syncUrlState() {
  const url = new URL(window.location.href);
  const params = url.searchParams;
  ["regione", "provincia", "comune"].forEach((key) => params.delete(key));
  if (state.currentRegione) params.set("regione", state.currentRegione);
  if (state.currentProvincia) params.set("provincia", state.currentProvincia);
  if (state.currentComuneIstat) params.set("comune", state.currentComuneIstat);
  window.history.replaceState({}, "", url);
  renderShareBar();
}

// Text that doesn't depend on drill-down state - nav, page intro, search
// placeholder. Everything else is rebuilt by render() itself, since it's
// templated HTML generated from state rather than static markup.
function applyStaticTranslations() {
  const lang = currentLang();
  document.documentElement.lang = lang;
  document.getElementById("lang-select").value = lang;
  document.title = `Stress in bici - ${t("statsNavLink")}`;
  document.getElementById("comuni-link").textContent = t("comuniNavLink");
  document.getElementById("stats-link").textContent = t("statsNavLink");
  document.getElementById("footer-credit").innerHTML = t("footerCredit");
  document.getElementById("footer-hosting-text").textContent = t("footerHosting");
  document.getElementById("page-title").textContent = t("statsPageTitle");
  document.getElementById("page-subtitle").textContent = t("statsPageSubtitle");
  document.getElementById("comune-search").placeholder = t("statsSearchPlaceholder");
  renderCoverageNote();
}

function renderCoverageNote() {
  const processed = state.regioni.reduce((s, r) => s + r.comuni_processed, 0);
  const regioniCount = state.regioni.length;
  const provinceCount = state.province.length;
  document.getElementById("coverage-note").textContent = t("statsCoverageNoteTemplate")(
    fmtInt(processed),
    ITALY_TOTAL_COMUNI,
    provinceCount,
    ITALY_TOTAL_PROVINCE,
    regioniCount,
    ITALY_TOTAL_REGIONI
  );
}

// --- Chart instance cache ----------------------------------------------

const chartInstances = new Map();
function getChart(containerId) {
  let inst = chartInstances.get(containerId);
  const el = document.getElementById(containerId);
  if (!el) return null;
  if (!inst || inst.getDom() !== el) {
    inst = echarts.init(el);
    chartInstances.set(containerId, inst);
  }
  return inst;
}
window.addEventListener("resize", () => {
  for (const inst of chartInstances.values()) inst.resize();
});

// --- Navigation / breadcrumb --------------------------------------------

function goRegione(regione) {
  state.currentRegione = regione;
  state.currentProvincia = null;
  state.currentComuneIstat = null;
  render();
}
function goProvincia(regione, provincia) {
  state.currentRegione = regione;
  state.currentProvincia = provincia;
  state.currentComuneIstat = null;
  render();
}
function goComune(istatCode) {
  const comune = state.comuni.find((c) => c.istat_code === istatCode);
  if (!comune) return;
  state.currentRegione = comune.regione;
  state.currentProvincia = comune.provincia;
  state.currentComuneIstat = istatCode;
  render();
}
function goRoot() {
  state.currentRegione = null;
  state.currentProvincia = null;
  state.currentComuneIstat = null;
  render();
}

function renderBreadcrumb() {
  const el = document.getElementById("breadcrumb");
  el.innerHTML = "";
  const crumbs = [{ label: t("statsBreadcrumbItalia"), onClick: goRoot }];
  if (state.currentRegione) crumbs.push({ label: state.currentRegione, onClick: () => goRegione(state.currentRegione) });
  if (state.currentProvincia) crumbs.push({ label: state.currentProvincia, onClick: () => goProvincia(state.currentRegione, state.currentProvincia) });
  if (state.currentComuneIstat) {
    const comune = state.comuni.find((c) => c.istat_code === state.currentComuneIstat);
    if (comune) crumbs.push({ label: comune.comune, onClick: null });
  }
  crumbs.forEach((c, i) => {
    if (i > 0) el.appendChild(document.createTextNode(" "));
    const btn = document.createElement("button");
    btn.textContent = c.label;
    const isLast = i === crumbs.length - 1;
    btn.disabled = isLast;
    if (!isLast) btn.addEventListener("click", c.onClick);
    el.appendChild(btn);
    if (!isLast) {
      const sep = document.createElement("span");
      sep.className = "crumb-sep";
      sep.textContent = "›";
      el.appendChild(sep);
    }
  });
}

function render() {
  syncUrlState();
  renderBreadcrumb();
  const root = document.getElementById("view-root");
  root.innerHTML = "";

  if (state.currentComuneIstat) {
    renderComuneDetail(root, state.currentComuneIstat);
    return;
  }
  if (state.currentProvincia) {
    const items = state.comuni.filter((c) => c.provincia === state.currentProvincia);
    renderLevelView(root, items, "comune", t("statsComuniOfTemplate")(state.currentProvincia));
    return;
  }
  if (state.currentRegione) {
    const items = state.province.filter((p) => p.regione === state.currentRegione);
    renderLevelView(root, items, "provincia", t("statsProvinceOfTemplate")(state.currentRegione));
    return;
  }
  renderLevelView(root, state.regioni, "regione", t("statsRootTitle"));
}

function itemName(row, level) {
  return level === "comune" ? row.comune : row.area;
}
function itemKey(row, level) {
  return level === "comune" ? row.istat_code : row.area;
}

// --- Level view: charts + table ------------------------------------------

function renderLevelView(root, items, level, title) {
  if (!items.length) {
    root.innerHTML += `<p>${t("statsNoDataForSelection")}</p>`;
    return;
  }

  const section = document.createElement("div");
  section.innerHTML = `<h2 style="margin:0 0 10px">${title}</h2>`;
  root.appendChild(section);

  const grid = document.createElement("div");
  grid.className = "charts-grid";
  grid.innerHTML = `
    <div class="card-panel">
      <h2>${t("statsChartRankedTitle")}</h2>
      <p class="chart-note">${t("statsChartRankedNote")}</p>
      <div id="chart-ranked" class="chart-box" style="height:${Math.max(220, items.length * 22)}px"></div>
    </div>
    <div class="card-panel">
      <h2>${t("statsChartLtsStackTitle")}</h2>
      <p class="chart-note">${t("statsChartLtsStackNote")}</p>
      <div id="chart-lts-stack" class="chart-box" style="height:${Math.max(220, items.length * 22)}px"></div>
    </div>
    <div class="card-panel">
      <h2>${t("statsChartExcludedTitle")}</h2>
      <p class="chart-note">${t("statsChartExcludedNote")}</p>
      <div id="chart-excluded" class="chart-box" style="height:${Math.max(220, items.length * 22)}px"></div>
    </div>
    <div class="card-panel">
      <h2>${t("statsChartDensityTitle")}</h2>
      <p class="chart-note">${t("statsChartDensityNote")}</p>
      <div id="chart-density" class="chart-box" style="height:${Math.max(220, items.length * 22)}px"></div>
    </div>
    ${items.some((r) => r.popolazione) ? `
    <div class="card-panel">
      <h2>${t("statsChartPerCapitaTitle")}</h2>
      <p class="chart-note">${t("statsChartPerCapitaNote")}</p>
      <div id="chart-per-capita" class="chart-box" style="height:${Math.max(220, items.length * 22)}px"></div>
    </div>` : ""}
    <div class="card-panel">
      <h2>${t("statsChartScatterTitle")}</h2>
      <p class="chart-note">${t("statsChartScatterNote")}</p>
      <div id="chart-scatter" class="chart-box" style="height:320px"></div>
    </div>
  `;
  root.appendChild(grid);

  const treemapPanel = document.createElement("div");
  treemapPanel.className = "card-panel";
  treemapPanel.innerHTML = `
    <h2>${t("statsChartTreemapTitle")}</h2>
    <p class="chart-note">${t("statsChartTreemapNote")}</p>
    <div id="chart-treemap" class="chart-box" style="height:420px"></div>
  `;
  root.appendChild(treemapPanel);

  drawRankedBar(items, level);
  drawLtsStack(items, level);
  drawExcludedStack(items, level);
  drawDensity(items, level);
  if (items.some((r) => r.popolazione)) drawPerCapita(items, level);
  drawScatter(items, level);
  drawTreemap(items, level);

  renderTable(root, items, level);
}

// Horizontal-bar charts reserve a fixed left margin for the category
// (name) axis labels - fine on desktop, but on a narrow phone screen a
// 160px label column leaves almost nothing for the bars themselves.
// hideOverlap on the value axis additionally lets echarts drop whichever
// tick labels would collide instead of letting them smash together.
function hbarLayout() {
  const narrow = window.innerWidth < 600;
  return { left: narrow ? 90 : 160, labelWidth: narrow ? 80 : 150 };
}

function drawRankedBar(items, level) {
  const chart = getChart("chart-ranked");
  const sorted = [...items].sort((a, b) => (a.low_stress_share ?? 0) - (b.low_stress_share ?? 0));
  const layout1 = hbarLayout();
  chart.setOption(
    {
      grid: { left: layout1.left, right: 40, top: 10, bottom: 20 },
      xAxis: { type: "value", max: 1, axisLabel: { formatter: (v) => `${Math.round(v * 100)}%`, hideOverlap: true } },
      yAxis: { type: "category", data: sorted.map((r) => itemName(r, level)), axisLabel: { width: layout1.labelWidth, overflow: "truncate" } },
      tooltip: {
        trigger: "item",
        formatter: (p) => {
          const row = sorted[p.dataIndex];
          return t("statsRankedTooltipTemplate")(p.name, fmtPercent(p.value), fmtKm(row.low_stress_km), fmtKm(row.total_km));
        },
      },
      series: [
        {
          type: "bar",
          data: sorted.map((r) => ({ value: r.low_stress_share ?? 0, itemStyle: { color: shareToColor(r.low_stress_share) } })),
          barMaxWidth: 18,
        },
      ],
    },
    true
  );
  chart.off("click");
  chart.on("click", (p) => onItemActivate(sorted[p.dataIndex], level));
}

function drawLtsStack(items, level) {
  const chart = getChart("chart-lts-stack");
  const sorted = [...items].sort((a, b) => (b.total_km ?? 0) - (a.total_km ?? 0));
  const series = ["0", "1", "2", "3", "4"].map((cls) => ({
    name: ltsLabel(cls),
    type: "bar",
    stack: "lts",
    itemStyle: { color: LTS_COLORS[cls] },
    data: sorted.map((r) => (r.km_by_lts && r.km_by_lts[cls]) || 0),
  }));
  const layout2 = hbarLayout();
  chart.setOption(
    {
      grid: { left: layout2.left, right: 40, top: 10, bottom: 20 },
      xAxis: { type: "value", axisLabel: { formatter: (v) => `${v} km`, hideOverlap: true } },
      yAxis: { type: "category", data: sorted.map((r) => itemName(r, level)), axisLabel: { width: layout2.labelWidth, overflow: "truncate" } },
      tooltip: { trigger: "axis", axisPointer: { type: "shadow" } },
      series,
    },
    true
  );
  chart.off("click");
  chart.on("click", (p) => onItemActivate(sorted[p.dataIndex], level));
}

function drawExcludedStack(items, level) {
  const chart = getChart("chart-excluded");
  const fields = excludedFields();
  const sorted = [...items].sort((a, b) => nonCyclableKm(b) - nonCyclableKm(a));
  const series = fields.map((f) => ({
    name: f.label,
    type: "bar",
    stack: "excl",
    itemStyle: { color: f.color },
    data: sorted.map((r) => f.value(r)),
  }));
  const layout2 = hbarLayout();
  chart.setOption(
    {
      grid: { left: layout2.left, right: 40, top: 10, bottom: 20 },
      xAxis: { type: "value", axisLabel: { formatter: (v) => `${v} km`, hideOverlap: true } },
      yAxis: { type: "category", data: sorted.map((r) => itemName(r, level)), axisLabel: { width: layout2.labelWidth, overflow: "truncate" } },
      tooltip: { trigger: "axis", axisPointer: { type: "shadow" } },
      series,
    },
    true
  );
  chart.off("click");
  chart.on("click", (p) => onItemActivate(sorted[p.dataIndex], level));
}

// Absolute km always favors whichever comune/provincia/regione is
// physically largest - not a useful ranking on its own. Two fair
// normalizations, shown as their own ranked charts rather than folded
// into the absolute-km one: density (km per km² of area) needs no data
// beyond what's already here, while the per-capita chart below (km per
// 1,000 residents) is the more direct answer to "which comune is
// actually well served", now that population_service.py sources ISTAT's
// POSAS bulk file.
function density(row) {
  return row.superficie_km2 ? row.total_km / row.superficie_km2 : 0;
}
function perCapita(row) {
  return row.popolazione ? (row.total_km / row.popolazione) * 1000 : 0;
}

function drawDensity(items, level) {
  const chart = getChart("chart-density");
  const sorted = [...items].sort((a, b) => density(a) - density(b));
  const layoutD = hbarLayout();
  chart.setOption(
    {
      grid: { left: layoutD.left, right: 40, top: 10, bottom: 20 },
      xAxis: { type: "value", axisLabel: { formatter: (v) => `${v}`, hideOverlap: true } },
      yAxis: { type: "category", data: sorted.map((r) => itemName(r, level)), axisLabel: { width: layoutD.labelWidth, overflow: "truncate" } },
      tooltip: { formatter: (p) => t("statsDensityTooltipTemplate")(p.name, density(sorted[p.dataIndex]).toFixed(2)) },
      series: [{ type: "bar", data: sorted.map((r) => Number(density(r).toFixed(2))), itemStyle: { color: "#3B4A7A" }, barMaxWidth: 18 }],
    },
    true
  );
  chart.off("click");
  chart.on("click", (p) => onItemActivate(sorted[p.dataIndex], level));
}

function drawPerCapita(items, level) {
  const chart = getChart("chart-per-capita");
  const withPop = items.filter((r) => r.popolazione);
  const sorted = [...withPop].sort((a, b) => perCapita(a) - perCapita(b));
  const layoutP = hbarLayout();
  chart.setOption(
    {
      grid: { left: layoutP.left, right: 40, top: 10, bottom: 20 },
      xAxis: { type: "value", axisLabel: { formatter: (v) => `${v}`, hideOverlap: true } },
      yAxis: { type: "category", data: sorted.map((r) => itemName(r, level)), axisLabel: { width: layoutP.labelWidth, overflow: "truncate" } },
      tooltip: { formatter: (p) => t("statsPerCapitaTooltipTemplate")(p.name, perCapita(sorted[p.dataIndex]).toFixed(2)) },
      series: [{ type: "bar", data: sorted.map((r) => Number(perCapita(r).toFixed(2))), itemStyle: { color: "#26A69A" }, barMaxWidth: 18 }],
    },
    true
  );
  chart.off("click");
  chart.on("click", (p) => onItemActivate(sorted[p.dataIndex], level));
}

// Single-level treemap (whatever `items` is showing at the current drill
// depth) rather than one giant regione->provincia->comune tree - lets the
// user zoom in one level at a time via goRegione/goProvincia/goComune,
// same as every other chart on this page, instead of a separate
// always-3-deep visualization that only ever made sense at the Italia
// root.
function drawTreemap(items, level) {
  const chart = getChart("chart-treemap");
  const data = items.map((r) => ({
    name: itemName(r, level),
    value: r.total_km,
    itemStyle: { color: shareToColor(r.low_stress_share) },
  }));
  chart.setOption(
    {
      tooltip: { formatter: (p) => t("statsTreemapTooltipTemplate")(p.name, fmtKm(p.value)) },
      series: [
        {
          type: "treemap",
          roam: false,
          nodeClick: false,
          breadcrumb: { show: false },
          data,
        },
      ],
    },
    true
  );
  chart.off("click");
  chart.on("click", (p) => {
    const row = items.find((r) => itemName(r, level) === p.name);
    onItemActivate(row, level);
  });
}

function drawScatter(items, level) {
  const chart = getChart("chart-scatter");
  const maxKm = Math.max(1, ...items.map((r) => r.total_km || 0));
  chart.setOption(
    {
      grid: { left: 55, right: 20, top: 20, bottom: 45 },
      xAxis: { type: "value", name: t("statsScatterXAxis"), min: 0, max: 1, axisLabel: { formatter: (v) => `${Math.round(v * 100)}%` } },
      yAxis: { type: "value", name: t("statsScatterYAxis") },
      tooltip: {
        formatter: (p) => t("statsScatterTooltipTemplate")(p.data.name, fmtPercent(p.data.value[0]), fmtKm(p.data.value[1]), fmtKm(p.data.value[2])),
      },
      series: [
        {
          type: "scatter",
          symbolSize: (val) => 8 + 32 * Math.sqrt((val[2] || 0) / maxKm),
          data: items.map((r) => ({
            name: itemName(r, level),
            value: [r.low_stress_share ?? 0, r.priority_intervention_km ?? 0, r.total_km ?? 0],
            itemStyle: { color: shareToColor(r.low_stress_share), opacity: 0.75 },
          })),
        },
      ],
    },
    true
  );
  chart.off("click");
  chart.on("click", (p) => onItemActivate(items[p.dataIndex], level));
}

function onItemActivate(row, level) {
  if (!row) return;
  if (level === "regione") goRegione(row.area);
  else if (level === "provincia") goProvincia(row.regione, row.area);
  else goComune(row.istat_code);
}

// --- Level view: sortable/filterable table --------------------------------

function levelColumns(level) {
  const common = [
    { key: "superficie_km2", label: t("statsColSuperficie"), format: fmtKm2 },
    { key: "popolazione", label: t("statsColPopolazione"), format: (v) => fmtInt(v) },
    { key: "total_km", label: t("statsColKmRete"), format: fmtKm },
    { key: "low_stress_km", label: t("statsColKmBassoStress"), format: fmtKm },
    { key: "low_stress_share", label: t("statsColQuota"), format: fmtPercent },
    { key: "km_per_km2", label: t("statsColKmPerKm2"), compute: density, format: (v) => v.toFixed(2) },
    { key: "km_per_1000_ab", label: t("statsColKmPer1000Ab"), compute: perCapita, format: (v) => v.toFixed(2) },
    { key: "priority_intervention_km", label: t("statsColKmPrioritari"), format: fmtKm },
    { key: "separated_path_km", label: t("statsColKmSeparate"), format: fmtKm },
  ];
  if (level === "comune") {
    return [
      { key: "comune", label: t("statsColComune"), isName: true },
      { key: "provincia", label: t("statsColProvincia") },
      { key: "regione", label: t("statsColRegione") },
      ...common,
    ];
  }
  const coverageCol = { key: "coverage_pct", label: t("statsColCopertura"), format: (v, r) => t("statsCoverageValueTemplate")(fmtInt(r.comuni_processed), fmtInt(r.comuni_total), v ?? 0) };
  if (level === "provincia") {
    return [
      { key: "area", label: t("statsColProvincia"), isName: true },
      { key: "regione", label: t("statsColRegione") },
      ...common,
      coverageCol,
    ];
  }
  return [
    { key: "area", label: t("statsColRegione"), isName: true },
    ...common,
    coverageCol,
  ];
}

// Shared 20-rows-per-page control for both the level table and the
// per-comune street table - a comune/provincia/regione list or a street
// list can run into the hundreds, and rendering (and scrolling through)
// all of it at once makes the page unreadable.
const PAGE_SIZE = 20;
function renderPager(containerId, page, totalPages, onChange) {
  const el = document.getElementById(containerId);
  el.innerHTML = "";
  if (totalPages <= 1) return;
  const prev = document.createElement("button");
  prev.type = "button";
  prev.textContent = "‹";
  prev.disabled = page <= 1;
  prev.addEventListener("click", () => onChange(page - 1));
  const label = document.createElement("span");
  label.textContent = `${page} / ${totalPages}`;
  const next = document.createElement("button");
  next.type = "button";
  next.textContent = "›";
  next.disabled = page >= totalPages;
  next.addEventListener("click", () => onChange(page + 1));
  el.append(prev, label, next);
}

function renderTable(root, items, level) {
  const wrap = document.createElement("div");
  wrap.className = "card-panel";
  const columns = levelColumns(level);
  wrap.innerHTML = `
    <div id="filters-row">
      <input type="text" id="table-filter" placeholder="${t("statsTableFilterPlaceholder")}" />
      <label style="display:flex;align-items:center;gap:6px;font-size:12px;color:#555">
        <input type="checkbox" id="table-select-all" /> ${t("statsTableSelectAllLabel")}
      </label>
    </div>
    <div class="table-wrap">
      <table class="data-table">
        <thead><tr id="table-head"></tr></thead>
        <tbody id="table-body"></tbody>
      </table>
    </div>
    <div id="table-pager" class="pager"></div>
  `;
  root.appendChild(wrap);

  let sortKey = columns.find((c) => c.key === "low_stress_share") ? "low_stress_share" : columns[0].key;
  let sortAsc = false;
  let filterText = "";
  let page = 1;

  function sortValue(row, key) {
    const col = columns.find((c) => c.key === key);
    return col && col.compute ? col.compute(row) : row[key];
  }

  function renderHead() {
    const row = document.getElementById("table-head");
    row.innerHTML = "";
    const checkTh = document.createElement("th");
    checkTh.className = "col-check";
    checkTh.textContent = "";
    row.appendChild(checkTh);
    for (const col of columns) {
      const th = document.createElement("th");
      th.textContent = col.label;
      if (col.key === sortKey) {
        th.classList.add("sorted");
        th.setAttribute("data-arrow", sortAsc ? "▲" : "▼");
      }
      row.appendChild(th);
    }
  }
  // Sort-toggle click handlers, attached separately from renderHead()
  // (rather than inline via addEventListener there) so a re-render of
  // the head - which rebuilds every <th> from scratch - never leaves a
  // stale listener from the previous render also firing.
  function attachHeadHandlers() {
    document.querySelectorAll("#table-head th:not(.col-check)").forEach((th, i) => {
      th.onclick = () => {
        const col = columns[i];
        if (sortKey === col.key) sortAsc = !sortAsc;
        else { sortKey = col.key; sortAsc = false; }
        page = 1;
        renderHead();
        attachHeadHandlers();
        renderBody();
      };
    });
  }

  function renderBody() {
    const tbody = document.getElementById("table-body");
    tbody.innerHTML = "";
    let rows = items.filter((r) => itemName(r, level).toLowerCase().includes(filterText));
    rows.sort((a, b) => {
      const av = sortValue(a, sortKey), bv = sortValue(b, sortKey);
      let cmp;
      if (typeof av === "string" || typeof bv === "string") cmp = String(av ?? "").localeCompare(String(bv ?? ""));
      else cmp = (av ?? -Infinity) - (bv ?? -Infinity);
      return sortAsc ? cmp : -cmp;
    });
    const totalPages = Math.max(1, Math.ceil(rows.length / PAGE_SIZE));
    page = Math.min(page, totalPages);
    const pageRows = rows.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
    renderPager("table-pager", page, totalPages, (p) => {
      page = p;
      renderBody();
    });
    for (const row of pageRows) {
      const tr = document.createElement("tr");
      const key = itemKey(row, level);
      const checkTd = document.createElement("td");
      checkTd.className = "col-check";
      const checkbox = document.createElement("input");
      checkbox.type = "checkbox";
      checkbox.checked = state.compare.level === level && state.compare.items.has(key);
      checkbox.addEventListener("click", (e) => {
        e.stopPropagation();
        toggleCompare(level, key, itemName(row, level), row);
      });
      checkTd.appendChild(checkbox);
      tr.appendChild(checkTd);

      columns.forEach((col) => {
        const td = document.createElement("td");
        if (col.isName) {
          const badges = row.capoluogo_regione
            ? `<span class="badge">${t("statsBadgeCapoluogoRegione")}</span>`
            : row.capoluogo_provincia
            ? `<span class="badge">${t("statsBadgeCapoluogoProvincia")}</span>`
            : "";
          td.innerHTML = `<span class="row-name">${row[col.key]}</span>${badges}`;
        } else {
          const raw = col.compute ? col.compute(row) : row[col.key];
          td.textContent = col.format ? col.format(raw, row) : raw ?? "-";
        }
        tr.appendChild(td);
      });
      tr.addEventListener("click", () => onItemActivate(row, level));
      tbody.appendChild(tr);
    }
  }

  document.getElementById("table-filter").addEventListener("input", (e) => {
    filterText = e.target.value.trim().toLowerCase();
    page = 1;
    renderBody();
  });
  document.getElementById("table-select-all").addEventListener("change", (e) => {
    const rows = items.filter((r) => itemName(r, level).toLowerCase().includes(filterText));
    if (e.target.checked) rows.forEach((r) => addToCompare(level, itemKey(r, level), itemName(r, level), r));
    else rows.forEach((r) => removeFromCompare(itemKey(r, level)));
    renderBody();
  });

  renderHead();
  attachHeadHandlers();
  renderBody();
}

// --- Comune detail -----------------------------------------------------

// --- Embedded priority-interventions map (comune detail only) --------------
//
// maplibre-gl/pmtiles are loaded on demand (same loadScriptOnce pattern
// app.js uses for turf/jspdf/ngraph) rather than unconditionally in
// <head>, since most visits to this page never open a comune detail at
// all - loading a ~250KB map library for a page that's mostly charts and
// tables would be wasted weight on every other view.
const scriptLoadPromises = new Map();
function loadScriptOnce(src) {
  if (!scriptLoadPromises.has(src)) {
    scriptLoadPromises.set(src, new Promise((resolve, reject) => {
      const script = document.createElement("script");
      script.src = src;
      script.onload = () => resolve();
      script.onerror = () => {
        scriptLoadPromises.delete(src);
        reject(new Error(`Failed to load script: ${src}`));
      };
      document.head.appendChild(script);
    }));
  }
  return scriptLoadPromises.get(src);
}
let maplibreLoadPromise = null;
function ensureMaplibreLoaded() {
  if (window.maplibregl && window.pmtiles) return Promise.resolve();
  if (!maplibreLoadPromise) {
    if (!document.getElementById("maplibre-css")) {
      const link = document.createElement("link");
      link.id = "maplibre-css";
      link.rel = "stylesheet";
      link.href = "../assets/vendor/maplibre-gl-5.24.0.css";
      document.head.appendChild(link);
    }
    maplibreLoadPromise = Promise.all([
      loadScriptOnce("../assets/vendor/maplibre-gl-5.24.0.js"),
      loadScriptOnce("../assets/vendor/pmtiles-4.5.0.js"),
    ]);
  }
  return maplibreLoadPromise;
}

let comuniIndexPromise = null;
function loadComuniIndex() {
  if (!comuniIndexPromise) comuniIndexPromise = loadJson("../data/comuni_index.json");
  return comuniIndexPromise;
}

let pmtilesProtocol = null;
let priorityMapInstance = null;
// True once the map itself is initialized enough to call setFilter/
// fitBounds on it - reset per comune. A row click that lands before this
// flips just queues the request instead of erroring on a half-built map.
let priorityMapReady = false;
let pendingFocusStreetName = null;
let pendingFocusStreetBbox = null;

// This map shows ONLY the priority-intervention streets (is_gap_edge,
// excluding has_parallel_cycleway) - not the comune's whole road network
// - per the user's own correction: a full LTS-colored base layer buried
// the actual point of the map. Streets are colored by their own LTS
// (almost always 3/4 - is_gap_edge edges are by definition high-stress).
// Clicking a row in the streets table below (renderInterventions'
// renderRows) calls focusPriorityStreet(), which re-filters the
// "priority-selected" layers to just that street and fits the map to it
// - same dark-case/yellow highlight app.js uses for its own single
// manually-selected gap street (GAP_SELECTION_COLOR/
// GAP_SELECTION_CASE_COLOR), applied here to whichever street was
// clicked instead of "all of them at once" (an earlier version of this
// map did that; the user asked for selection-driven highlighting tied to
// the table instead).
const PRIORITY_SELECTED_CASE_COLOR = "#1A1A1A";
const PRIORITY_SELECTED_COLOR = "#FFD60A";
// Matches no real feature (an empty `name` never appears - unnamed gap
// edges are filtered out before this map's source data is even queried
// for the table), so both selection layers start invisible until a
// street is actually clicked.
const NO_STREET_FILTER = ["==", ["get", "name"], ""];

function renderPriorityMapLegend(container) {
  const items = ["3", "4"].map(
    (cls) => `<span><span class="legend-swatch" style="background:${LTS_COLORS[cls]}"></span>${ltsLabel(cls)}</span>`
  );
  items.push(`<span class="legend-highlight"><span class="legend-swatch"></span>${t("statsPriorityMapSelectedLegend")}</span>`);
  container.innerHTML = items.join("");
}

// Called from renderInterventions' table rows and the top-10 chart.
// Re-filters the selection layers to just this street and fits the map
// to its `bbox` - precomputed server-side (build_comuni_interventions.py,
// [minlon, minlat, maxlon, maxlat]) rather than found by querying the
// map's already-loaded vector tiles at the CURRENT view/zoom
// (map.querySourceFeatures), which is what an earlier version of this
// did. That broke silently for most streets: the map's initial view
// spans the whole comune, at a zoom where tippecanoe's own tiling only
// includes major roads (see pmtiles_edges_service.py's module docstring
// on the "any zoom>=12" filter) - a residential gap-edge street simply
// isn't in ANY tile loaded yet at that zoom, so the query found nothing
// and the map just didn't move. Only the top-10-by-length chart's
// entries (skewed toward bigger, more prominent streets that DO show at
// low zoom) happened to work, which is exactly the "only the ones in the
// bar chart" symptom reported. A precomputed bbox sidesteps the whole
// loaded-tiles/zoom dependency.
function focusPriorityStreet(name, bbox) {
  if (!priorityMapInstance || !priorityMapReady) {
    pendingFocusStreetName = name;
    pendingFocusStreetBbox = bbox;
    return;
  }
  const map = priorityMapInstance;
  const filter = ["==", ["get", "name"], name];
  if (map.getLayer("priority-selected-case")) map.setFilter("priority-selected-case", filter);
  if (map.getLayer("priority-selected")) map.setFilter("priority-selected", filter);

  if (bbox) {
    map.fitBounds(
      [
        [bbox[0], bbox[1]],
        [bbox[2], bbox[3]],
      ],
      { padding: 60, maxZoom: 17 }
    );
    return;
  }
  // Fallback for an interventions JSON generated before bbox was added -
  // best-effort, only works if the street happens to already be in a
  // loaded tile (see comment above).
  const features = map.querySourceFeatures("lts", { sourceLayer: "lts", filter });
  if (!features.length) return;
  const bounds = new window.maplibregl.LngLatBounds();
  for (const feature of features) {
    const geom = feature.geometry;
    const lines = geom.type === "MultiLineString" ? geom.coordinates : [geom.coordinates];
    for (const line of lines) for (const coord of line) bounds.extend(coord);
  }
  map.fitBounds(bounds, { padding: 60, maxZoom: 17 });
}

async function renderPriorityMap(comune) {
  priorityMapReady = false;
  pendingFocusStreetName = null;
  pendingFocusStreetBbox = null;
  const mapPanel = document.getElementById("priority-map-panel");
  if (!mapPanel) return; // user already navigated away while this was loading
  const container = document.getElementById("priority-map");
  const legend = document.getElementById("priority-map-legend");

  if (priorityMapInstance) {
    priorityMapInstance.remove();
    priorityMapInstance = null;
  }

  let comuniIndex, maplibregl, pmtiles;
  try {
    [comuniIndex] = await Promise.all([loadComuniIndex(), ensureMaplibreLoaded()]);
    ({ maplibregl } = window);
    ({ pmtiles } = window);
  } catch (error) {
    container.innerHTML = `<p>${t("statsInterventionsUnavailable")}</p>`;
    return;
  }
  // The panel may have been torn down (user navigated to another comune)
  // while the awaits above were in flight - bail rather than initializing
  // a map into a detached container.
  if (!document.getElementById("priority-map-panel")) return;

  const indexEntry = comuniIndex.find((e) => e.istat === comune.istat_code);
  if (!indexEntry) {
    container.innerHTML = `<p>${t("statsInterventionsUnavailable")}</p>`;
    return;
  }

  if (!pmtilesProtocol) {
    pmtilesProtocol = new pmtiles.Protocol();
    maplibregl.addProtocol("pmtiles", pmtilesProtocol.tile);
  }
  const slug = indexEntry.slug;
  const pmtilesHref = new URL(`../data/${slug}_lts.pmtiles`, window.location.href).toString();
  const tiles = new pmtiles.PMTiles(pmtilesHref);
  pmtilesProtocol.add(tiles);

  const map = new maplibregl.Map({
    container: "priority-map",
    style: "https://styles.maptoolkit.org/light.json",
    bounds: indexEntry.bbox,
    fitBoundsOptions: { padding: 20 },
  });
  priorityMapInstance = map;
  map.addControl(new maplibregl.NavigationControl({ showCompass: false }), "top-right");

  map.on("load", () => {
    if (priorityMapInstance !== map) return; // superseded by a later comune before tiles finished loading
    map.addSource("lts", { type: "vector", url: `pmtiles://${pmtilesHref}` });

    // Only priority-intervention edges are drawn at all (is_gap_edge,
    // excluding has_parallel_cycleway) - unnamed ones included here even
    // though they don't get a row in the table below (no name to list/
    // click), so the map still shows the full picture of what's flagged.
    const priorityFilter = ["all", ["==", ["to-string", ["get", "is_gap_edge"]], "true"], ["!=", ["to-string", ["get", "has_parallel_cycleway"]], "true"]];
    map.addLayer({
      id: "priority-only-lines",
      type: "line",
      source: "lts",
      "source-layer": "lts",
      filter: priorityFilter,
      layout: { "line-join": "round", "line-cap": "round" },
      paint: {
        "line-color": ["match", ["to-string", ["get", "lts"]], "1", LTS_COLORS["1"], "2", LTS_COLORS["2"], "3", LTS_COLORS["3"], "4", LTS_COLORS["4"], LTS_COLORS["0"]],
        "line-width": ["interpolate", ["linear"], ["zoom"], 10, 1.5, 16, 4],
      },
    });
    // Selection layers: invisible (NO_STREET_FILTER) until a table row
    // is clicked (focusPriorityStreet), added after priority-only-lines
    // so they always draw on top of it.
    map.addLayer({
      id: "priority-selected-case",
      type: "line",
      source: "lts",
      "source-layer": "lts",
      filter: NO_STREET_FILTER,
      layout: { "line-join": "round", "line-cap": "round" },
      paint: { "line-color": PRIORITY_SELECTED_CASE_COLOR, "line-width": ["interpolate", ["linear"], ["zoom"], 10, 3, 16, 7] },
    });
    map.addLayer({
      id: "priority-selected",
      type: "line",
      source: "lts",
      "source-layer": "lts",
      filter: NO_STREET_FILTER,
      layout: { "line-join": "round", "line-cap": "round" },
      paint: { "line-color": PRIORITY_SELECTED_COLOR, "line-width": ["interpolate", ["linear"], ["zoom"], 10, 1.5, 16, 4] },
    });

    const popup = new maplibregl.Popup({ closeButton: false, maxWidth: "240px" });
    for (const layerId of ["priority-only-lines", "priority-selected"]) {
      map.on("mouseenter", layerId, () => { map.getCanvas().style.cursor = "pointer"; });
      map.on("mouseleave", layerId, () => { map.getCanvas().style.cursor = ""; popup.remove(); });
      map.on("click", layerId, (e) => {
        const props = e.features[0].properties;
        popup
          .setLngLat(e.lngLat)
          .setHTML(`<strong>${props.name || "-"}</strong><br/>LTS ${props.lts}`)
          .addTo(map);
      });
    }

    // Ready as soon as the layers exist - setFilter/fitBounds don't need
    // tiles to have actually finished loading (unlike the old
    // querySourceFeatures approach this replaced, which did and was the
    // whole reason this readiness gate existed in the first place).
    priorityMapReady = true;
    if (pendingFocusStreetName) {
      focusPriorityStreet(pendingFocusStreetName, pendingFocusStreetBbox);
      pendingFocusStreetName = null;
      pendingFocusStreetBbox = null;
    }
  });

  renderPriorityMapLegend(legend);
}

function renderComuneDetail(root, istatCode) {
  const comune = state.comuni.find((c) => c.istat_code === istatCode);
  if (!comune) {
    root.innerHTML = `<p>${t("statsComuneNotFound")}</p>`;
    return;
  }

  const badges = [
    comune.capoluogo_regione ? `<span class="badge">${t("statsBadgeCapoluogoDiRegione")}</span>` : "",
    !comune.capoluogo_regione && comune.capoluogo_provincia ? `<span class="badge">${t("statsBadgeCapoluogoDiProvincia")}</span>` : "",
  ].join("");

  const header = document.createElement("div");
  header.innerHTML = `<h2 style="margin:0 0 4px">${comune.comune}${badges}</h2>
    <p style="color:#666;margin:0 0 10px">${comune.provincia} · ${comune.regione}</p>
    <p style="margin:0 0 14px"><a class="nav-link" href="../index.html?area=${encodeURIComponent(areaSlug(comune.comune))}" target="_blank" rel="noopener">${t("statsOpenInMap")} →</a></p>`;
  root.appendChild(header);

  const kpiRow = document.createElement("div");
  kpiRow.id = "kpi-row";
  kpiRow.innerHTML = [
    [t("statsKpiSuperficie"), fmtKm2(comune.superficie_km2)],
    [t("statsKpiPopolazione"), fmtInt(comune.popolazione)],
    [t("statsKpiKmRete"), fmtKm(comune.total_km)],
    [t("statsKpiQuota"), fmtPercent(comune.low_stress_share)],
    [t("statsKpiKmPrioritario"), fmtKm(comune.priority_intervention_km)],
    [t("statsKpiKmSeparate"), fmtKm(comune.separated_path_km)],
    [t("statsKpiNonCyclable"), fmtKm(nonCyclableKm(comune))],
    [t("statsKpiIsole"), fmtInt(comune.low_stress_island_count)],
  ]
    .map(([label, value]) => `<div class="kpi-card"><div class="kpi-label">${label}</div><div class="kpi-value">${value}</div></div>`)
    .join("");
  root.appendChild(kpiRow);

  const grid = document.createElement("div");
  grid.className = "charts-grid";
  grid.innerHTML = `
    <div class="card-panel">
      <h2>${t("statsComuneLtsTitle")}</h2>
      <div id="chart-comune-lts" class="chart-box" style="height:230px"></div>
    </div>
    <div class="card-panel">
      <h2>${t("statsComuneExcludedTitle")}</h2>
      <div id="chart-comune-excluded" class="chart-box" style="height:230px"></div>
    </div>
  `;
  root.appendChild(grid);

  const ltsChart = getChart("chart-comune-lts");
  ltsChart.setOption({
    grid: { left: 10, right: 40, top: 45, bottom: 60 },
    xAxis: { type: "value", position: "top", axisLabel: { formatter: (v) => `${v} km` } },
    yAxis: { type: "category", data: [comune.comune], axisLabel: { show: false } },
    tooltip: { trigger: "item" },
    series: ["0", "1", "2", "3", "4"].map((cls) => ({
      name: ltsLabel(cls),
      type: "bar",
      stack: "lts",
      itemStyle: { color: LTS_COLORS[cls] },
      data: [(comune.km_by_lts && comune.km_by_lts[cls]) || 0],
    })),
    legend: { bottom: 0, left: "center", textStyle: { fontSize: 10 } },
  }, true);

  const exclChart = getChart("chart-comune-excluded");
  exclChart.setOption({
    grid: { left: 10, right: 40, top: 45, bottom: 60 },
    xAxis: { type: "value", position: "top", axisLabel: { formatter: (v) => `${v} km` } },
    yAxis: { type: "category", data: [comune.comune], axisLabel: { show: false } },
    tooltip: { trigger: "item" },
    series: excludedFields().map((f) => ({
      name: f.label,
      type: "bar",
      stack: "excl",
      itemStyle: { color: f.color },
      data: [f.value(comune)],
    })),
    legend: { bottom: 0, left: "center", textStyle: { fontSize: 10 } },
  }, true);

  const interventionsPanel = document.createElement("div");
  interventionsPanel.className = "card-panel";
  interventionsPanel.innerHTML = `<h2>${t("statsInterventionsTitle")}</h2><p class="chart-note">${t("statsInterventionsLoading")}</p>`;
  root.appendChild(interventionsPanel);

  loadJson(`../data/interventions/${istatCode}.json`)
    .then((data) => renderInterventions(interventionsPanel, data))
    .catch(() => {
      interventionsPanel.innerHTML = `<h2>${t("statsInterventionsTitle")}</h2><p>${t("statsInterventionsUnavailable")}</p>`;
    });

  // Placed after the interventions panel (not before it) so the map
  // that visualizes "Vie con interventi prioritari" reads as a follow-up
  // to that list, not a preview of it - the user's own ordering.
  const mapPanel = document.createElement("div");
  mapPanel.className = "card-panel";
  mapPanel.id = "priority-map-panel";
  mapPanel.innerHTML = `
    <h2>${t("statsPriorityMapTitle")}</h2>
    <p class="chart-note">${t("statsPriorityMapNote")}</p>
    <div id="priority-map"></div>
    <div id="priority-map-legend"></div>
  `;
  root.appendChild(mapPanel);
  renderPriorityMap(comune);
}

function renderInterventions(panel, data) {
  const streets = data.streets || [];
  const highwayKm = data.highway_km || {};

  panel.innerHTML = `
    <h2>${t("statsHighwayCompositionTitle")}</h2>
    <p class="chart-note">${t("statsHighwayCompositionNote")}</p>
    <div id="chart-highway" class="chart-box" style="height:${Math.max(160, Object.keys(highwayKm).length * 24)}px"></div>
    <h2 style="margin-top:20px">${t("statsInterventionsTitle")}</h2>
    <p class="chart-note">${t("statsPriorityStreetsNote")}</p>
    ${streets.length ? `<p class="chart-note">${t("statsPriorityChartCaptionTemplate")(Math.min(streets.length, 10), streets.length)}</p>` : ""}
    ${streets.length ? `<div id="chart-streets" class="chart-box" style="height:${Math.min(streets.length, 10) * 28 + 40}px"></div>` : `<p>${t("statsNoNamedStreets")}</p>`}
    ${streets.length ? `
    <div id="filters-row" style="margin-top:14px">
      <input type="text" id="street-filter" placeholder="${t("statsStreetFilterPlaceholder")}" />
    </div>
    <div class="table-wrap">
      <table class="data-table" id="streets-table">
        <thead><tr>
          <th data-key="name">${t("statsColVia")}</th>
          <th data-key="lts">${t("statsColLts")}</th>
          <th data-key="centrality">${t("statsColCentralita")}</th>
          <th data-key="length_km">${t("statsColKm")}</th>
          <th data-key="edge_count">${t("statsColNTratti")}</th>
          <th data-key="highway">${t("statsColTipo")}</th>
        </tr></thead>
        <tbody id="streets-body"></tbody>
      </table>
    </div>
    <div id="streets-pager" class="pager"></div>` : ""}
  `;

  const highwayEntries = Object.entries(highwayKm).sort((a, b) => b[1] - a[1]);
  const highwayChart = getChart("chart-highway");
  const layoutH = hbarLayout();
  highwayChart.setOption(
    {
      grid: { left: layoutH.left, right: 40, top: 10, bottom: 20 },
      xAxis: { type: "value", axisLabel: { formatter: (v) => `${v} km`, hideOverlap: true } },
      yAxis: { type: "category", data: highwayEntries.map(([k]) => highwayLabel(k)).reverse(), axisLabel: { width: layoutH.labelWidth, overflow: "truncate" } },
      series: [{ type: "bar", data: highwayEntries.map(([, v]) => v).reverse(), itemStyle: { color: "#3B4A7A" }, barMaxWidth: 18 }],
    },
    true
  );

  if (!streets.length) return;

  const top10 = streets.slice(0, 10);
  const streetsChart = getChart("chart-streets");
  const layoutS = hbarLayout();
  streetsChart.setOption(
    {
      grid: { left: layoutS.left, right: 40, top: 10, bottom: 20 },
      xAxis: { type: "value", axisLabel: { formatter: (v) => `${v} km`, hideOverlap: true } },
      yAxis: { type: "category", data: top10.map((s) => s.name).reverse(), axisLabel: { width: layoutS.labelWidth, overflow: "truncate" } },
      tooltip: { formatter: (p) => t("statsStreetTooltipTemplate")(p.name, top10[top10.length - 1 - p.dataIndex].lts, fmtKm(p.value)) },
      series: [
        {
          type: "bar",
          data: top10.map((s) => ({ value: s.length_km, itemStyle: { color: LTS_COLORS[String(s.lts)] } })).reverse(),
          barMaxWidth: 18,
        },
      ],
    },
    true
  );
  streetsChart.off("click");
  streetsChart.on("click", (p) => {
    const street = top10[top10.length - 1 - p.dataIndex];
    focusPriorityStreet(street.name, street.bbox);
    document.getElementById("priority-map-panel")?.scrollIntoView({ behavior: "smooth", block: "nearest" });
  });

  let sortKey = "lts", sortAsc = false, filterText = "", streetsPage = 1;
  function renderRows() {
    const tbody = document.getElementById("streets-body");
    tbody.innerHTML = "";
    let rows = streets.filter((s) => s.name.toLowerCase().includes(filterText));
    rows.sort((a, b) => {
      const av = a[sortKey], bv = b[sortKey];
      let cmp = typeof av === "string" ? String(av).localeCompare(String(bv)) : (av ?? 0) - (bv ?? 0);
      return sortAsc ? cmp : -cmp;
    });
    const totalPages = Math.max(1, Math.ceil(rows.length / PAGE_SIZE));
    streetsPage = Math.min(streetsPage, totalPages);
    const pageRows = rows.slice((streetsPage - 1) * PAGE_SIZE, streetsPage * PAGE_SIZE);
    renderPager("streets-pager", streetsPage, totalPages, (p) => {
      streetsPage = p;
      renderRows();
    });
    for (const s of pageRows) {
      const tr = document.createElement("tr");
      tr.innerHTML = `
        <td class="row-name">${s.name}</td>
        <td><span class="street-lts-badge" style="background:${LTS_COLORS[String(s.lts)]}">${s.lts}</span></td>
        <td>${centralityLabel(s.centrality_class)}</td>
        <td>${fmtKm(s.length_km)}</td>
        <td>${fmtInt(s.edge_count)}</td>
        <td>${highwayLabel(s.highway)}</td>
      `;
      tr.style.cursor = "pointer";
      tr.title = t("statsPriorityMapZoomHint");
      tr.addEventListener("click", () => {
        focusPriorityStreet(s.name, s.bbox);
        const mapPanel = document.getElementById("priority-map-panel");
        if (mapPanel) mapPanel.scrollIntoView({ behavior: "smooth", block: "nearest" });
      });
      tbody.appendChild(tr);
    }
  }
  document.querySelectorAll("#streets-table th").forEach((th) => {
    th.addEventListener("click", () => {
      const key = th.dataset.key;
      if (sortKey === key) sortAsc = !sortAsc;
      else { sortKey = key; sortAsc = false; }
      streetsPage = 1;
      renderRows();
    });
  });
  document.getElementById("street-filter").addEventListener("input", (e) => {
    filterText = e.target.value.trim().toLowerCase();
    streetsPage = 1;
    renderRows();
  });
  renderRows();
}

// --- Search box ----------------------------------------------------------

function setupSearch() {
  const input = document.getElementById("comune-search");
  const results = document.getElementById("search-results");
  input.addEventListener("input", () => {
    const q = input.value.trim().toLowerCase();
    if (q.length < 2) {
      results.classList.add("hidden");
      return;
    }
    const matches = state.comuni.filter((c) => c.comune.toLowerCase().includes(q)).slice(0, 15);
    if (!matches.length) {
      results.innerHTML = `<div>${t("statsSearchNoResults")}</div>`;
      results.classList.remove("hidden");
      return;
    }
    results.innerHTML = matches
      .map(
        (c, i) =>
          `<div data-idx="${i}"><strong>${c.comune}</strong> <span class="sr-meta">${c.provincia} · ${c.regione}</span></div>`
      )
      .join("");
    results.classList.remove("hidden");
    results.querySelectorAll("div[data-idx]").forEach((div) => {
      div.addEventListener("click", () => {
        const c = matches[Number(div.dataset.idx)];
        input.value = "";
        results.classList.add("hidden");
        goComune(c.istat_code);
      });
    });
  });
  document.addEventListener("click", (e) => {
    if (!e.target.closest("#search-wrap")) results.classList.add("hidden");
  });
}

// --- Compare tray + modal --------------------------------------------------

function toggleCompare(level, key, name, row) {
  if (state.compare.items.has(key)) removeFromCompare(key);
  else addToCompare(level, key, name, row);
}

function addToCompare(level, key, name, row) {
  if (state.compare.level && state.compare.level !== level) {
    state.compare.items.clear();
  }
  state.compare.level = level;
  state.compare.items.set(key, { name, row });
  renderCompareTray();
}

function removeFromCompare(key) {
  state.compare.items.delete(key);
  if (!state.compare.items.size) state.compare.level = null;
  renderCompareTray();
}

// --- Share bar (always-visible copy-link + socials) ------------------------
//
// Reuses the exact URL builders and inline-SVG icons web/app.js's own
// ShareControl modal uses (same brand colors, same platforms) for visual
// consistency, but as a persistent fixed bar rather than a toggled
// panel, and pointed at THIS page's own URL (kept in sync with the
// current drill-down by syncUrlState) - no need for app.js's compact
// base64 ?c= encoding here, since this page's shareable state is just
// three plain, readable query params.
const SOCIAL_SHARE_URL_BUILDERS = {
  facebook: (url) => `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`,
  linkedin: (url) => `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`,
  x: (url, text) => `https://twitter.com/intent/tweet?url=${encodeURIComponent(url)}&text=${encodeURIComponent(text)}`,
  whatsapp: (url, text) => `https://wa.me/?text=${encodeURIComponent(`${text} ${url}`)}`,
};

function setupShareBar() {
  document.getElementById("share-copy-link").addEventListener("click", async (e) => {
    const url = window.location.href;
    try {
      await navigator.clipboard.writeText(url);
      const btn = e.currentTarget;
      const original = btn.title;
      btn.title = t("shareCopied");
      setTimeout(() => { btn.title = original; }, 1500);
    } catch (error) {
      window.prompt(t("statsShareCopyFallback"), url);
    }
  });
}

function renderShareBar() {
  const url = window.location.href;
  const text = t("shareIntentText");
  document.getElementById("share-social-facebook").href = SOCIAL_SHARE_URL_BUILDERS.facebook(url);
  document.getElementById("share-social-linkedin").href = SOCIAL_SHARE_URL_BUILDERS.linkedin(url);
  document.getElementById("share-social-x").href = SOCIAL_SHARE_URL_BUILDERS.x(url, text);
  document.getElementById("share-social-whatsapp").href = SOCIAL_SHARE_URL_BUILDERS.whatsapp(url, text);
}

function setupCompareTray() {
  document.getElementById("compare-clear").addEventListener("click", () => {
    state.compare.items.clear();
    state.compare.level = null;
    renderCompareTray();
    render();
  });
  document.getElementById("compare-open").addEventListener("click", openCompareModal);
  document.getElementById("compare-close").addEventListener("click", closeCompareModal);
  document.getElementById("compare-modal-backdrop").addEventListener("click", (e) => {
    if (e.target.id === "compare-modal-backdrop") closeCompareModal();
  });
}

function compareLevelLabel() {
  return { regione: t("statsCompareLevelRegioni"), provincia: t("statsCompareLevelProvince"), comune: t("statsCompareLevelComuni") }[state.compare.level];
}

function renderCompareTray() {
  const tray = document.getElementById("compare-tray");
  document.body.classList.toggle("compare-active", state.compare.items.size > 0);
  document.getElementById("compare-open").textContent = t("statsCompareButton");
  document.getElementById("compare-clear").textContent = t("statsCompareClear");
  if (!state.compare.items.size) {
    tray.classList.add("hidden");
    return;
  }
  tray.classList.remove("hidden");
  document.getElementById("compare-label").textContent = t("statsCompareLabelTemplate")(compareLevelLabel());
  const chips = document.getElementById("compare-chips");
  chips.innerHTML = "";
  for (const [key, { name }] of state.compare.items) {
    const chip = document.createElement("span");
    chip.className = "compare-chip";
    chip.textContent = name + " ✕";
    chip.style.cursor = "pointer";
    chip.addEventListener("click", () => {
      removeFromCompare(key);
      render();
    });
    chips.appendChild(chip);
  }
  document.getElementById("compare-open").disabled = state.compare.items.size < 2;
}

function openCompareModal() {
  if (state.compare.items.size < 2) return;
  const rows = [...state.compare.items.values()].map((v) => v.row);
  const level = state.compare.level;
  document.getElementById("compare-modal-title").textContent = t("statsCompareModalTitleTemplate")(compareLevelLabel());
  const body = document.getElementById("compare-modal-body");
  body.innerHTML = `
    <div id="chart-compare-share" class="chart-box" style="height:${Math.max(160, rows.length * 34)}px"></div>
    <div id="chart-compare-lts" class="chart-box" style="height:${Math.max(160, rows.length * 34)}px;margin-top:20px"></div>
  `;
  document.getElementById("compare-modal-backdrop").classList.remove("hidden");

  const shareChart = getChart("chart-compare-share");
  shareChart.setOption(
    {
      title: { text: t("statsCompareShareChartTitle"), left: "center", textStyle: { fontSize: 13 } },
      grid: { left: 140, right: 40, top: 40, bottom: 20 },
      xAxis: { type: "value", max: 1, axisLabel: { formatter: (v) => `${Math.round(v * 100)}%` } },
      yAxis: { type: "category", data: rows.map((r) => itemName(r, level)) },
      series: [{ type: "bar", data: rows.map((r) => ({ value: r.low_stress_share ?? 0, itemStyle: { color: shareToColor(r.low_stress_share) } })), barMaxWidth: 22 }],
    },
    true
  );

  const ltsChart = getChart("chart-compare-lts");
  ltsChart.setOption(
    {
      title: { text: t("statsCompareLtsChartTitle"), left: "center", textStyle: { fontSize: 13 } },
      grid: { left: 140, right: 40, top: 40, bottom: 20 },
      xAxis: { type: "value", axisLabel: { formatter: (v) => `${v} km` } },
      yAxis: { type: "category", data: rows.map((r) => itemName(r, level)) },
      legend: { top: 20 },
      series: ["0", "1", "2", "3", "4"].map((cls) => ({
        name: ltsLabel(cls),
        type: "bar",
        stack: "lts",
        itemStyle: { color: LTS_COLORS[cls] },
        data: rows.map((r) => (r.km_by_lts && r.km_by_lts[cls]) || 0),
      })),
    },
    true
  );
}

function closeCompareModal() {
  document.getElementById("compare-modal-backdrop").classList.add("hidden");
}
