from __future__ import annotations

import os

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import osmnx as ox

from .common import city_output_dir, load_graph, save_placeholder


NETWORK_OUTPUTS = [
    "nodes_degree_centrality.png",
    "nodes_closeness_centrality.png",
    "nodes_betweenness_centrality.png",
    "edge_betweenness_centrality.png",
    "lts_distrib_nodes_plot.png",
    "lts_distrib_edges_plot.png",
    "nodess_betweenness_centrality.png",
    "nodess_closeness_centrality.png",
    "edgez_betweenness_centrality.png",
    "deg_central_map.png",
    "deg_central_map_top_nodes.png",
    "clos_central_map.png",
    "clos_central_map_top_nodes.png",
    "betw_central_map.png",
    "betw_central_map_top_nodes.png",
    "edge_bet_central_map.png",
    "edge_bet_central_map_top_nodes.png",
    "g_high_stres_map.png",
    "component_1.png",
    "component_2.png",
    "component_3.png",
    "component_4.png",
    "component_5.png",
    "kde_est_simplifiedgraph.png",
    "nearest_poi_plot.png",
]


def run_network_analysis(data_dir: str, images_dir: str, area_slug: str) -> None:
    out_dir = city_output_dir(images_dir, area_slug)
    graph = load_graph(data_dir, area_slug)
    undirected = nx.Graph(graph)

    degree = nx.degree_centrality(undirected)
    closeness = nx.closeness_centrality(undirected)
    betweenness = nx.betweenness_centrality(undirected, k=min(250, max(10, len(undirected.nodes) // 10)))

    def _save_hist(values, title, name):
        plt.figure(figsize=(8, 4))
        plt.hist(list(values), bins=30, color="#4c78a8", edgecolor="white")
        plt.title(title)
        plt.tight_layout()
        plt.savefig(os.path.join(out_dir, name), dpi=200)
        plt.close()

    _save_hist(degree.values(), "Degree Centrality", "nodes_degree_centrality.png")
    _save_hist(closeness.values(), "Closeness Centrality", "nodes_closeness_centrality.png")
    _save_hist(betweenness.values(), "Betweenness Centrality", "nodes_betweenness_centrality.png")

    edge_lts = []
    for _, _, _, data in graph.edges(keys=True, data=True):
        try:
            edge_lts.append(int(data.get("lts", 0)))
        except Exception:
            edge_lts.append(0)

    _save_hist(edge_lts, "LTS Distribution - Edges", "lts_distrib_edges_plot.png")

    node_lts = []
    for _, data in graph.nodes(data=True):
        try:
            node_lts.append(int(data.get("lts", 0)))
        except Exception:
            node_lts.append(0)
    _save_hist(node_lts, "LTS Distribution - Nodes", "lts_distrib_nodes_plot.png")

    fig, ax = ox.plot_graph(graph, node_size=0, edge_linewidth=0.5, show=False, close=False)
    fig.savefig(os.path.join(out_dir, "g_high_stres_map.png"), dpi=200)
    plt.close(fig)

    for name in NETWORK_OUTPUTS:
        path = os.path.join(out_dir, name)
        if not os.path.exists(path):
            save_placeholder(path, f"Generated by network module: {name}")
